### ISSUE TITLE
Sending too many packets?

### ISSUE THREAD

**Issue by redd17** [Earthcomputer/clientcommands#10]
is there a way to do this on a friends server without "sending too many packets'" and disconnecting me?

**Comment by Vonr** [comment]
Try using a smaller number of pages. I would recommend /cbook random 13, followed by /cbook ascii, followed by /cbook random 7, followed by /cbook random 5. If none worked, I can't really help ya.

**Comment by Earthcomputer** [comment]
What he said.

**Comment by redd17** [comment]
thanks again for the help :)
