### ISSUE TITLE
branch_miner.js "action is not a function"

### ISSUE THREAD

**Issue by LexiTehGallade** [Earthcomputer/clientcommands#100]
I'm not technically inclined so I can't tell you why but this happens upon attempting to load the script without fail each and every time (see attached image) 
![image](https://user-images.githubusercontent.com/43154241/72819520-55f98200-3c65-11ea-837e-952302ccdcc5.png)

**Comment by Earthcomputer** [comment]
There should be an error in the game log, can you send it here?

**Comment by LexiTehGallade** [comment]
I would like to but i'm afraid I cannot even access my game when trying to run the latest version of the game (1.15.2) with the latest release as I ran into a new problem involving game crash - Would you like me to create a new issue for that first or have both issues together?

**Comment by Earthcomputer** [comment]
Please make sure you are on the latest version of clientcommands before reporting the crash, and then create a new issue for that crash if it still occurs. I still need the game logs for the "action is not a function" message.

**Comment by Lasagnenator** [comment]
[latest.log](https://github.com/Earthcomputer/clientcommands/files/4095469/latest.log)

This is the game log for action is not a function.

For context, I just loaded the world, ran /cscript run branch_mine.js, then exited. 

I would have tried it on 1.15.2 but I could not get clientcommands to work there due to a game crash on startup.

**Comment by Earthcomputer** [comment]
You guys really need to make an issue about this crash on startup. If you don't make an issue, it won't get fixed.

**Comment by LexiTehGallade** [comment]
Back on topic,
[relevant.log](https://github.com/Earthcomputer/clientcommands/files/4096707/relevant.log)
Here is my latest.log with all information regarding anything other than the script deleted. Hope it helps.

**Comment by Earthcomputer** [comment]
What Java version are you using? And is it oracle or openjdk?

**Comment by LexiTehGallade** [comment]
![image](https://user-images.githubusercontent.com/43154241/72890670-5861e780-3d0a-11ea-9234-14d85a92de8f.png)

**Comment by LexiTehGallade** [comment]
Addendum: Updated to latest oracle version, issue still happening.

**Comment by Earthcomputer** [comment]
I can't reproduce. Did you modify the script at all in any way?

**Comment by Lasagnenator** [comment]
I've narrowed the error down to the creation of the Thread objects at the end of the script. I believe `action` refers to the name of the parameter in the `Thread` constructor.

**Comment by LemmaEOF** [comment]
It seems like this might be a bug with Oracle JDK. Maybe try OpenJDK?

**Comment by Earthcomputer** [comment]
I tried running clientcommands with Oracle JDK 1.8.0_241, which is the latest Oracle JDK version available, and I still cannot reproduce the issue.

**Comment by Earthcomputer** [comment]
I asked a friend to try and reproduce it on Windows, they couldn't either.

**Comment by Lasagnenator** [comment]
Minecraft by default uses the bundled java runtime which for me is 1.8.0_51. So I forced it to use the installed java runtime and now it is working. 

This should be a part of the installation instructions for clientcommands or fabric that the user needs to change the used runtime to an installed one and not the bundled one if they plan on using the scripts.

**Comment by Earthcomputer** [comment]
I managed to reproduce on 1.8.0_51, will work on fixing it
