### ISSUE TITLE
/ccrackrng not working 1.8.9 spigot

### ISSUE THREAD

**Issue by Beaustromswastaken** [Earthcomputer/clientcommands#106]
Says it all in the title, it throws the items and says it is cracking but never actually cracks.

**Comment by Earthcomputer** [comment]
It should have also given you the following warning:
> Warning: the server you are playing on is modded. RNG features in this mod are not guaranteed to work!

Not sure why you think that means that it's guaranteed to work on a 1.8.9 Spigot server.
