### ISSUE TITLE
Add a fortune calculator to make sure every block you mine with fortune yields maximum output.

### ISSUE THREAD

**Issue by Neubulae** [Earthcomputer/clientcommands#107]
Tho is it possible theoretically? Since we have already entered the realms of RNG... Just askin'

**Comment by Earthcomputer** [comment]
It is within the realms of theoretical possibility, yes. However, the effort required on the part of the player is huge compared to enchantment cracking (you need a full perimeter, cleared out spawn chunks and no other players online) that I don't think any users of my mod would actually use it.

If you are on 1.12 or below, there is a much easier way to do this, and has been done on various technical Minecraft servers such as SciCraft and ProtoTech. I would recommend asking them for details.

**Comment by Neubulae** [comment]
> It is within the realms of theoretical possibility, yes. However, the effort required on the part of the player is huge compared to enchantment cracking (you need a full perimeter, cleared out spawn chunks and no other players online) that I don't think any users of my mod would actually use it.
> 
> If you are on 1.12 or below, there is a much easier way to do this, and has been done on various technical Minecraft servers such as SciCraft and ProtoTech. I would recommend asking them for details.

Ah ok, I see.

**Comment by leumasme** [comment]
#60

**Comment by Earthcomputer** [comment]
Denied for the reasons already stated
