### ISSUE TITLE
Port to the Rift Mod API as a temporary solution for 1.13.2

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#11]
It seems like Forge for 1.13 won't be available for a long time, so maybe the mod should be ported to the Rift Mod API (https://minecraft.curseforge.com/projects/rift) for 1.13 until Forge finally updates.

**Comment by Vonr** [comment]
Forge is already in beta. why dont you attempt it yourself? im on it but its taking longer than i have time for

**Comment by Earthcomputer** [comment]
I would actually like to skip 1.13 and port the mod to the Fabric loader once 1.14 is out. It doesn't look like Rift is going to make it very far tbh, and I don't like the direction Forge is taking, so Fabric it is.

**Comment by WaffleTraits** [comment]
I know that the WWE modded client (1.13.2) has a ported version of /cbook, maybe some other commands could be ported.

**Comment by Earthcomputer** [comment]
I personally don't have the time to maintain a mod for multiple Minecraft versions at once, and to update to a mod loader that is only going to exist for one version. I've already started the port to Fabric so everything is going to be available again for 1.14 ;)

**Comment by Wehsuh-Sushi** [comment]
where can i download the programm for rift?

**Comment by Earthcomputer** [comment]
As I have said already, it doesn't and will never exist for Rift. Wait for 1.14 to come out.

**Comment by EastArctica** [comment]
> As I have said already, it doesn't and will never exist for Rift. Wait for 1.14 to come out.

Comes out on Tuesday hows it going so far?

**Comment by Earthcomputer** [comment]
It's ported to 1.14 now
