### ISSUE TITLE
Enchanting in multiplayer server?

### ISSUE THREAD

**Issue by HandsomeWu007** [Earthcomputer/clientcommands#115]
When I type /ccrackrng, it threw 1 stacks of item and just stopped there. So, will it be possible to work in a 1.14.4 server.

**Comment by HandsomeWu007** [comment]
And a quick question, are you able to get mending in single player?

**Comment by MCRcortex** [comment]
Did it warn you that the server is modded?

**Comment by HandsomeWu007** [comment]
Emmm...    I dont think so

**Comment by MCRcortex** [comment]
well if the server has any plugins, its probably "modded" and running paper mc, client commands rng manipulation doesnt work with paper mc.

**Comment by HandsomeWu007** [comment]
It is a bungeecord server and i  dont think there is any plugin, unless the anti - cheat plugin.....

**Comment by MCRcortex** [comment]
yes its running paper then, and thus not supported by client commands rng manipulation

**Comment by Earthcomputer** [comment]
?template modded
