### ISSUE TITLE
Is it possible to get it to work on 1.16 snapshots by ourselves? 

### ISSUE THREAD

**Issue by utilitychase** [Earthcomputer/clientcommands#119]
I'm asking about it because I've got a server with my friends which is in the newest 1.16 Snapshot and I wondered if I could update it by myself to the newest Snapshot or if you can do it.

**Comment by MCRcortex** [comment]
of course you can get it working in 1.16 by yourself, however i am unsure how much time/how difficult it world be

**Comment by Earthcomputer** [comment]
I don't update clientcommands to snapshots. Of course you're free to do it yourself, but don't expect it to be easy if you don't have much modding experience.
