### ISSUE TITLE
/cglow doesnt have support for HEX codes with letters.

### ISSUE THREAD

**Issue by OneYellowLemon** [Earthcomputer/clientcommands#120]
/cglow doesnt have support for HEX codes with letters.

EX: `/cglow <entity> 1000000 colorCode 000000` will make whatever entity you choose glow black, but `/cglow <entity> 1000000 colorCode ffffff` will give an error message saying it wants you to supply an integer instead of glowing white

![Expected Integer](https://user-images.githubusercontent.com/66096725/84208931-dd178d00-aa82-11ea-8390-6222386981cd.png)

**Comment by leumasme** [comment]
You are entering it as a decimal number, not as a hex number.
To enter a hex number, you can use the standard hex number format, which is prefixing the number with "0x". Example:
/cglow @e[type=minecraft:chicken] 10 colorCode 0xffffff 
This will let all chickens glow white.
Alternatively, use the decimal equivalent of hex FFFFFF, which is 16777215
/cglow @e[type=minecraft:chicken] 10 colorCode 16777215

**Comment by OneYellowLemon** [comment]
Oh ok lol. Thanks!
