### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MineMasters555** [Earthcomputer/clientcommands#123]
I was trying the brench mining bot to work but i am keep having a error massage. could someone help? 
link to my log: https://paste.ubuntu.com/p/fQzxwFm63Y/
screen shot: 
![2020-06-16_17 16 47](https://user-images.githubusercontent.com/67012999/84793658-af3bc680-aff5-11ea-9b74-e0791c9ba8ee.png)

**Comment by Earthcomputer** [comment]
Please can you post:
1) your clientcommands version
2) your Java version

**Comment by MineMasters555** [comment]
clientcommands-2.3.7-pre6 (i have that in my mods file with fabric-api-0.11.1+build.312-1.15) and java version 8 update 251 (build 1.8.0_251-b08) oracle

**Comment by Earthcomputer** [comment]
Works as intended. The script itself is throwing the error, if you check line 355 of the script. In this case it looks like you forgot your torches.

**Comment by Earthcomputer** [comment]
Feel free to modify the script if it doesn't quite fit your uses. It's there as an example script for people to learn how to use clientcommands' scripting API.

**Comment by MineMasters555** [comment]
jup that was it i am new to this client command stuff thank you so much (:
