### ISSUE TITLE
crashing on server

### ISSUE THREAD

**Issue by MineMasters555** [Earthcomputer/clientcommands#124]
sorry for bothering you again.
i play on a vanilla minecraft server with some plugins one of them is spigot (not paper because i can enchantment crack). if i type in the command to start the script my game freezes and i get a not respond massage. it does work on single player do i need to change something in the code or what is wrong? I have 4gigs of ram allocated to minecraft. 
https://paste.ubuntu.com/p/z2zgXJDqtH/

**Comment by RobertasJ** [comment]
i dont know maybe earthcomputer can answer

**Comment by MineMasters555** [comment]
also the server has anti x-ray

**Comment by RobertasJ** [comment]
k
and is the server yours

**Comment by Earthcomputer** [comment]
And you show me your script?

**Comment by RobertasJ** [comment]
if that server is public and its not paper im in

**Comment by MineMasters555** [comment]
its a small server just for me and my friends. like a 6 person server. i didnt change the script. but ill send it anyway, i copyed the entire script and pasted it in a txt
[branch_mine.txt](https://github.com/Earthcomputer/clientcommands/files/4788074/branch_mine.txt)

**Comment by MineMasters555** [comment]
i just tested on a 100% vannila server and it didnt work.

**Comment by RobertasJ** [comment]
ok

**Comment by Earthcomputer** [comment]
?template stale

**Comment by Earthcomputer** [comment]
?template stale

**Comment by MineMasters555** [comment]
o sorry didnt know i needed to do it this way.
but i still have the same problem could you help please?

**Comment by Earthcomputer** [comment]
I asked you to show me your script, can you show me your script?

**Comment by MineMasters555** [comment]
i pasted in a txt file because i couldnt send it in the normal file type.
[branch_mine.txt](https://github.com/Earthcomputer/clientcommands/files/4821313/branch_mine.txt)

**Comment by Earthcomputer** [comment]
Oh, sorry, I missed that you posted it before, I'll take a look and see if I can reproduce it.
If everything works as intended, that script is supposed to do nothing at all, since you haven't actually called any functions. It shouldn't crash the game though.

**Comment by MineMasters555** [comment]
Did you managed to reproduce it?

**Comment by Earthcomputer** [comment]
I haven't got round to it yet. In the mean time you can make sure you don't use `Thread.currentThread ` without doing something else as well.

**Comment by MineMasters555** [comment]
No problem, how do I do that can I go in the code and put it to false?

**Comment by Earthcomputer** [comment]
Postponed because Java 15 has been released which doesn't include Nashorn, and I'll be rewriting the scripting component of clientcommands and this bug will likely disappear in that process.
