### ISSUE TITLE
multiplayer crashes 

### ISSUE THREAD

**Issue by MineMasters555** [Earthcomputer/clientcommands#126]
I play on a vanilla minecraft server with some plugins one of them is spigot (not paper because i can enchantment crack). if i type in the command to start the script my game freezes and i get a not respond massage. it does work on single player do i need to change something in the code or what is wrong? I have 4gigs of ram allocated to minecraft.
https://paste.ubuntu.com/p/z2zgXJDqtH/

**Comment by Earthcomputer** [comment]
Please do not open a second issue for the same problem, please comment on the old issue and respond to my query there.
Duplicate of #124
