### ISSUE TITLE
Ench manip not working

### ISSUE THREAD

**Issue by Beaustromsw** [Earthcomputer/clientcommands#127]
Hello! Before you say anything: this is entirely unmodded 1.16.1 with the proper client. There are no plugins installed. When doing a dummy enchantment it doesnt enchant but still tells me to do something. The ench manipulator then shows that my chosen enchantments should be on the item, but this is always wrong. It was working previously, i dont know what changed (possibly a bug on my end, but i would like to check).

**Comment by Beaustromsw** [comment]
also, it just worked, i was using a fishing rod as the dummy, i think that is what messed it up (i used a gold pickaxe instead and it worked)

**Comment by Earthcomputer** [comment]
The item you use as your dummy shouldn't make a difference.

**Comment by Beaustromsw** [comment]
another thing: probbably unfixable, but whenever i try to do long enchantments it crashes me. It did not do this before, which is why i am asking about it. prob just my computer being bad though

**Comment by Beaustromsw** [comment]
tested it again, thorns is what is messing it up apparently with the crashing

**Comment by Earthcomputer** [comment]
Have you managed to resolve this yet?
