### ISSUE TITLE
ccrackrng  sometimes not working

### ISSUE THREAD

**Issue by aria1th** [Earthcomputer/clientcommands#132]
It sometimes works but sometimes it totally works wrong way- maybe it's predicting 'next' enchantments instead of current enchantments. 

/ccrackrng + /cenchantment (things) would not work, but manually doing it with different type of tools would work correctly.

What I mean is, 

[with ccrackrng +cenchant command](https://youtu.be/z7kenA8sb2s)

with automatic enchantment cracking, it's missing something but

[with manual cracking+ cenchant](https://youtu.be/MxAW1KtBPiw)

semi-manual way, it would work.

The server is carpet mod fabric server, so I guess it should not change any things with enchantments. I'm not getting any potion effects or beacon effects.

**Comment by leumasme** [comment]
Your manual video is one second long

**Comment by aria1th** [comment]
whut... something has broken. I'll reupload asap

**Comment by aria1th** [comment]
https://youtu.be/MNg6Xb6pCfI

**Comment by OneYellowLemon** [comment]
Notice when you did the automatic cracking it said to use 14 bookshelves and you had 15. Make sure to remove one of them, you just got lucky with random chance on the manual one that it still worked with 15 instead of 12.

**Comment by OneYellowLemon** [comment]
@aria1th 
Did you try it with only the amount of bookshelves asked?

**Comment by aria1th** [comment]
yeah, it fails by 30% chance. Not only blast resistance, netherite pickaxe had the problem, with 15 bookshelves needed.

**Comment by OneYellowLemon** [comment]
I don't have any issues with it, could you upload a video of you doing it but with the correct number of bookshelves?

**Comment by aria1th** [comment]
https://www.youtube.com/watch?v=0VioFmS-uOw

Unless I'm not numbering properly, it's failing, but it also successes for most of the time. Since I'm doing that stuff 50+ times, I guess I did not do any don't-things. 

But well, it 100% successes for diamond tools.

**Comment by OneYellowLemon** [comment]
Hmmm, do you know what mods are installed server-side?

**Comment by aria1th** [comment]
Carpet mod, Carpet extra(accurateblockplacement), and phosphor & Lithium, servux.

**Comment by MCRcortex** [comment]
all i can say is that if you can accurately do /ccrackrng then either items are using separate rng from the player or the enchanting stuff is different than vanilla

**Comment by westlyroots** [comment]
can confirm I am getting this too, only Fabric and the API on a Realms server. Manual RNG cracking works

**Comment by OneYellowLemon** [comment]
Why use Fabric if you have no mods other than the API?

**Comment by westlyroots** [comment]
> Why use Fabric if you have no mods other than the API?

I removed other mods to eliminate any possible compatibility issues

**Comment by Earthcomputer** [comment]
> can confirm I am getting this too, only Fabric and the API on a Realms server. Manual RNG cracking works

It doesn't work on Realms

**Comment by Earthcomputer** [comment]
@aria1th is this still an issue? I noticed in the videos that you are not paying attention to the exact number of bookshelves, which *can* cause issues. Also, what carpet rules do you have enabled?
