### ISSUE TITLE
/cglow effect on an item frame is indefinite (unlike with other entities)

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#137]
Minecraft 1.16.1
carpet-extra-1.16-1.4.0
clearview-2.1
clientcommands-2.4.3
fabric-api-0.14.1+build.372-1.16
fabric-carpet-1.16-1.4.0+v200623
lithium-fabric-mc1.16.1-0.5.1
notenoughcrashes-1.2.4+1.16.1
phosphor-fabric-mc1.16.1-0.6.0+build.7
sodium-fabric-mc1.16.1-0.1.0

When you use `/cglow` on an item frame, the glow remains indefinitely until the item frame is unloaded, irrespective of the time parameter passed into the command.

To reproduce:
1. Summon or find an item frame and any other entity.
2. Run the command: `/cglow @e`.
3. All entities will now glow for about 20 seconds.
4. However, once all other entities have stopped glowing, any item frames that were glowing remain glowing indefinitely.
5. Unload the entities by logging out or using `/tp @p ~999 ~ ~`.
6. Reload the entities by logging back in or using `/tp @p ~-999 ~ ~`.
7. Notice the item frame's glowing effect has been cleared.

**Comment by Earthcomputer** [comment]
Please update to the latest version of clientcommands and let me know if this is still an issue.

**Comment by James103** [comment]
I updated clientcommands to 2.4.4, and then ran `/cglow @e 1` while looking at an item frame. Other entities glowed for 1 seconds, but the item frame remained glowing much longer than that. The item frame still needed to be reloaded before it stopped glowing.

**Comment by User670** [comment]
Mine cart with chest also glows indefinitely.

**Comment by James103** [comment]
> Mine cart with chest also glows indefinitely.

This also occurs with all types of minecarts.

**Comment by Sanluli36li** [comment]
leads on fence too
