### ISSUE TITLE
/cfindblock crashes the client

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#139]
Minecraft 1.16.1
carpet-extra-1.16-1.4.0
clearview-2.1
clientcommands-2.4.4
fabric-api-0.14.1+build.372-1.16
fabric-carpet-1.16-1.4.0+v200623
lithium-fabric-mc1.16.1-0.5.1
notenoughcrashes-1.2.4+1.16.1
phosphor-fabric-mc1.16.1-0.6.0+build.7
sodium-fabric-mc1.16.1-0.1.0

Every time you do `/cfindblock`, it crashes the client no matter what as of clientcommands-2.4.4. `/cfindblock` did not crash when run using clientcommands-2.3.3. The crash occurs no matter what is passed in for the argument, as long as it is a valid block type or tag. More specifically, it crashes exactly here (last modified in 9caf937513990a3311901ba20f650f3bd0fd56b0):
https://github.com/Earthcomputer/clientcommands/blob/7e1b3727be51d479f689031b646b3b5827a4fba0/src/main/java/net/earthcomputer/clientcommands/command/arguments/ClientBlockPredicateArgumentType.java#L18

Last four crash reports:
[crash-2020-08-12_17.07.00-client.txt](https://github.com/Earthcomputer/clientcommands/files/5066157/crash-2020-08-12_17.07.00-client.txt)
[crash-2020-08-12_17.10.07-client.txt](https://github.com/Earthcomputer/clientcommands/files/5066158/crash-2020-08-12_17.10.07-client.txt)
[crash-2020-08-12_17.09.44-client.txt](https://github.com/Earthcomputer/clientcommands/files/5066159/crash-2020-08-12_17.09.44-client.txt)
[crash-2020-08-12_17.09.12-client.txt](https://github.com/Earthcomputer/clientcommands/files/5066160/crash-2020-08-12_17.09.12-client.txt)

**Comment by Earthcomputer** [comment]
clientcommands 2.4.4 requires Minecraft 1.16.2, please update.
