### ISSUE TITLE
I need help book dupe glitch

### ISSUE THREAD

**Issue by Reachy99** [Earthcomputer/clientcommands#140]
Server is running 1.7.x to 1.8.x i can't find clientcommands for that versions so what should i do to get those books. I tried autohotkey script but when i run it, script start to write 50 pages but they are empty. Because of that i want to write books with cbook random 50 but i can't find version for 1.7.x to 1.8.x , can someone help pls?

**Comment by Earthcomputer** [comment]
If you want to port it yourself feel free
