### ISSUE TITLE
how do i turn off RNG manipulation?

### ISSUE THREAD

**Issue by zax71** [Earthcomputer/clientcommands#143]
after i enchanted something with this mod (using enchanting table) i got the message RNG manipulated, reason: sprinted (or something like that). is there any way to turn this off?

**Comment by LemonatedCat** [comment]
Turn what off exactly?

**Comment by LemonatedCat** [comment]
Sprinting Changes your RNG in a way the client can't reliably predict, So we loose the RNG seed and you have to re-crack.

Do not sprint.

**Comment by zax71** [comment]
I don’t really need this mod anyway, I’m going to close it I think

**Comment by zax71** [comment]
> Sprinting Changes your RNG in a way the client can't reliably predict, So we loose the RNG seed and you have to re-crack.
> 
> Do not sprint.

But, I don’t want RNG manipulation

**Comment by LemonatedCat** [comment]
Why did you enable it then? There is a temprule you need to enable for it to be turned on

**Comment by zax71** [comment]
Huh, strange I’ve never turned it on

**Comment by Earthcomputer** [comment]
If you don't want RNG manipulation, then why did you even crack the seed lmao. That message only shows up if you have the seed cracked. You don't just crack the seed by accident. And you don't enable temp rules by accident either.

**Comment by zax71** [comment]
I NEVER changed any game rules, I installed the mod for, /ccalcatack and have used nothing else, so, is it a bug?

**Comment by leumasme** [comment]
You are likely using an outdated version where disabling enchantment prediction is not a thing yet.
Only the version for the latest Minecraft version will be updated (1.16.2 rn)

**Comment by zax71** [comment]
Ah, I’m using a 1.16 release not 1.16.2 bit running on 1.16.2
