### ISSUE TITLE
Idea: Ability to toggle client-side Night Vision

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#144]
What if there was an option/command to allow you to toggle client-side Night Vision? There would be two possible options to achieve this: the default option which matches existing vanilla behavior with respect to the Night Vision effect, as well as the new option to always render as if you had the Night Vision effect.

This can be useful to allow you to search caves and other dark spots easier. Depending on technicalities, the effect could persist between you changing dimensions, but it would always reset to default when you (re-)join a server or world.

**Comment by Earthcomputer** [comment]
`/cgamma 16`
