### ISSUE TITLE
/cnote &4RED (and other codes)

### ISSUE THREAD

**Issue by fakename131** [Earthcomputer/clientcommands#147]
I would make a pull request if i made fabric mods but I only make plugins, but anyways:
could u add '&' color codes to /cnote

**Comment by Earthcomputer** [comment]
No, this isn't Spigot, & codes are an awful idea. Maybe an alternative could be found like some modified markdown

**Comment by fakename131** [comment]
i know this isnt spigot, thats why i said i would *not* make a pull request, i dont make fabric mods bcuz when i tried, the src main rescorces didnt work

**Comment by haykam821** [comment]
Would the [Markdown Chat mod](https://github.com/Gegy/markdown-chat)'s syntax work? It uses `^eText^` for color codes and normal Markdown for other formatting.

**Comment by Earthcomputer** [comment]
Feature denied, sorry. /cnote is meant for taking notes, not sure why you particularly need formatting in them.
