### ISSUE TITLE
Commands like csetblock

### ISSUE THREAD

**Issue by Dorapower** [Earthcomputer/clientcommands#153]
Maybe it's possible to change the client world through modding? Using this feature we can simply get some fake blocks/ghost blocks, sometimes it will be useful.
And we can airhop if we can automatically place block beneath.

**Comment by Earthcomputer** [comment]
Remember that clientcommands is not a hacked client, and the purpose of such a command will never be "air hopping" or stuff like that. But I can see a use for being able to place arbitrary ghost blocks for technical Minecraft.

**Comment by Earthcomputer** [comment]
`/cghostblock` in the next release
