### ISSUE TITLE
You can do "cenchant --simulate --simulate" when "--simulate" should only be allowed once

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#164]
Tested on Client Commands 2.4.8 for Minecraft 1.16.4

Command and example output (actual):
![image](https://user-images.githubusercontent.com/37945304/103470275-5552e200-4d36-11eb-89bb-0722a580a168.png)

Expected: Not to allow `--simulate` flag twice

**Comment by Earthcomputer** [comment]
I couldn't find a way to fix this issue with brigadier, if anyone has any ideas please let me know. In the mean time it's not the end of the world (I think, as long as we don't have a repeat of 2020).

**Comment by James103** [comment]
In other words, try replicating the following command structure:
`/cenchant --simulate <itemAndEnchantmentsPredicate>`
`/cenchant <itemAndEnchantmentsPredicate>`

Current command structure:
`/cenchant --simulate -> cenchant`
`/cenchant <itemAndEnchantmentsPredicate>`

**Comment by Earthcomputer** [comment]
Oh I understand the issue, the problem is what to do instead.

**Comment by barraIhsan** [comment]
also, we can do `/cfinditem --keep-searching --keep-searching` (also apply to no-shulker-box)

**Comment by James103** [comment]
This code allows for `/cenchant --simulate --simulate`:
https://github.com/Earthcomputer/clientcommands/blob/a0cb4484f708e4aa927bac6ce0597ebee72fc2c8/src/main/java/net/earthcomputer/clientcommands/command/CEnchantCommand.java#L26-L28

This code allows for `/cfinditem --keep-searching --keep-searching` and `/cfinditem --no-search-shulker-box --no-search-shulker-box`:
https://github.com/Earthcomputer/clientcommands/blob/a0cb4484f708e4aa927bac6ce0597ebee72fc2c8/src/main/java/net/earthcomputer/clientcommands/command/FindItemCommand.java#L61-L65

This code allows for `/cfind --keep-searching --keep-searching`:
https://github.com/Earthcomputer/clientcommands/blob/f8e96da566e2a34f427aa033ef7ccd6c707e7eaf/src/main/java/net/earthcomputer/clientcommands/command/FindCommand.java#L31-L33

This code allows for `/cglow --keep-searching-entities --keep-searching-entities`:
https://github.com/Earthcomputer/clientcommands/blob/f8e96da566e2a34f427aa033ef7ccd6c707e7eaf/src/main/java/net/earthcomputer/clientcommands/command/GlowCommand.java#L47-L49

In all of the above cases which I could find, there is a `.redirect(...)` back to the start of the command, akin to the following syntax:
```
/cenchant --simulate -> cenchant
/cfinditem --keep-searching -> cfinditem
/cfinditem --no-search-shulker-box -> cfinditem
/cfind --keep-searching -> cfind
/cglow --keep-searching-entities -> cglow
```

**Comment by Earthcomputer** [comment]
Yes it's obvious what code is causing it, however it is much less obvious how to actually fix it.

**Comment by Domkeykong** [comment]
This now includes `/ccalc`
```
/ccalc --parse -> ccalc
```

**Comment by xpple** [comment]
#260 might come with a way to fix this.
