### ISSUE TITLE
fishing rng does not work with ping higher than 100ms

### ISSUE THREAD

**Issue by aria1th** [Earthcomputer/clientcommands#165]
seems its maximum considered ping is limited to 100ms and does not consider ping over that

condition : constant ping with 300ms+-10%
target : any enchanted goals
result : tries to manipulate but it always fail with +100ms offset

**Comment by radiant-ai** [comment]
Yes, it just writes that fishing bobber is out of water when ping is too high

**Comment by holysnipz** [comment]
<details>
<summary>original post:</summary>

using both release and [this commit](https://github.com/Earthcomputer/clientcommands/commit/2754416817fd7d2851edecb3ccf7fc26287f9f49)
target: mending ench. book

modded server, not even reach 50ms.
![image](https://user-images.githubusercontent.com/9103583/105506070-3b386e00-5cfc-11eb-8480-5c73a54ea4fc.png)

rarely got the correct one
![image](https://user-images.githubusercontent.com/9103583/105507945-615f0d80-5cfe-11eb-9012-1d702169ef88.png)

got both "bobber is out of water" and "wrong loot" consistently
![image](https://user-images.githubusercontent.com/9103583/105506133-4c817a80-5cfc-11eb-9d06-22cb36458c7f.png)
![image](https://user-images.githubusercontent.com/9103583/105506407-98342400-5cfc-11eb-88c6-61045df2b1d2.png)

</details>

edit: lily pad does the trick for me, thanks for clarification.

**Comment by Earthcomputer** [comment]
You need to fish under a lily pad to stop the bobber going out of water. You need to wait for the fishing client to calibrate before you start consistently getting correct loot. It does work with ping higher than 100ms.
