### ISSUE TITLE
Running clientcommands on Java 15

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#176]
As of now, command /cscript does not work on Java 15, because dependency Nashorn was removed from jdk.

This can be fixed 

- by adding [dependency](https://search.maven.org/artifact/org.openjdk.nashorn/nashorn-core/15.1/jar), 
- modifying imports to work with this dependency, for example from
`import jdk.nashorn.api.scripting.AbstractJSObject;`
to
`import org.openjdk.nashorn.api.scripting.AbstractJSObject;`,

- and changing paths on lines 49 and 50 in `ScriptManager.java` to
`Class<?> factoryCls = Class.forName("org.openjdk.nashorn.api.scripting.NashornScriptEngineFactory");`
`Class<?> classFilterCls = Class.forName("org.openjdk.nashorn.api.scripting.ClassFilter");`

**Comment by Earthcomputer** [comment]
Postponing this issue due to plans to split off this mod in 1.17, as an addon for JSMacros, which will solve this problem.

**Comment by xpple** [comment]
I think this can be closed now.
