### ISSUE TITLE
I added a /cspeed command, and some others, but I don't know if I should make a pull request...

### ISSUE THREAD

**Issue by Mr-Sbev** [Earthcomputer/clientcommands#179]
I added a /cspeed command, a /cdab command, a /cclip command, and a /cvclip command. Should I make a pull request?

**Comment by Earthcomputer** [comment]
If you have already added them then why not?

**Comment by Mr-Sbev** [comment]
OK! I just realized that the speed increases exponentially every tick in my code, so I'm trying to think of some ways to mitigate that... Also, I'm not sure how to make a pull request but ill figure that out...

**Comment by Mr-Sbev** [comment]
it works by setting the velocity (v) to v * speed, but it does that every tick

**Comment by Mr-Sbev** [comment]
so I need to fix that

**Comment by Mr-Sbev** [comment]
What should I have the acceleration rate be?

**Comment by Mr-Sbev** [comment]
Oh and also, what should I do with negative numbers?
