### ISSUE TITLE
/cfinditem does not search other inventories if you have item already in inventory

### ISSUE THREAD

**Issue by Anunayj** [Earthcomputer/clientcommands#18]
I was just thinking won't it be useful if /cfinditem still searched other inventories even if you had the item in your inventory already.
https://github.com/Earthcomputer/clientcommands/blob/master/src/main/java/net/earthcomputer/clientcommands/command/CommandFindItem.java#L71

**Comment by Earthcomputer** [comment]
Implemented in 1.14
