### ISSUE TITLE
Add --keep-searching option to /cfindblock

### ISSUE THREAD

**Issue by Spacebarium** [Earthcomputer/clientcommands#182]
For example, `/cfindblock spawner --i 20` would run the command every 20 seconds. Not sure how many commands this could be realistically applied to

**Comment by Earthcomputer** [comment]
Why not run it every tick?

**Comment by Spacebarium** [comment]
I find that `cfindblock` can cause really big lagspikes when unable to find any nearby so running it every tick wouldn't be so great

Also just realised the scripting feature can do exactly this so maybe this can be used for shorter activities that don't need a whole script?

**Comment by Mr-Sbev** [comment]
We could have --i 20 be every 20 ticks...

**Comment by 0f-0b** [comment]
Why not `cinterval <time> <command>`, where `<time>` is a [`minecraft:time`](https://minecraft.gamepedia.com/Argument_types#minecraft:time)?

**Comment by LemonatedCat** [comment]
We probably want to exclude any already found blocks

**Comment by Earthcomputer** [comment]
We could also just... ya know... optimize cfindblock --keep-searching so it doesnt lag the game out

**Comment by Mr-Sbev** [comment]
It would be cool to add a cinterval command that could run any command on an interval...

**Comment by Earthcomputer** [comment]
That sounds like a pretty fringe usecase that you can already do with /cscript

**Comment by Mr-Sbev** [comment]
I should probably learn how to use 
/cscript

**Comment by Earthcomputer** [comment]
Changing this to a --keep-searching option, which seems to better reflect the problem you actually want to solve.
