### ISSUE TITLE
/cattrib command for modifying player attributes in singleplayer

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#191]
https://minecraft.gamepedia.com/Attribute#Vanilla_modifiers

or maybe /cdata as the vanilla command is /data

**Comment by James103** [comment]
The full command name should be `/cattribute` and syntax should be as follows:
`/cattribute get <attribute>` gets the final value of one of your attributes.
`/cattribute base get <attribute>` gets the base value of one of your attributes.

Note that you could just use `/cgetdata` to get the values of your attributes (or another client-side entity's attributes).

**Comment by xpple** [comment]
Outdated as of 1.16
