### ISSUE TITLE
/cscript didn't work

### ISSUE THREAD

**Issue by yts233** [Earthcomputer/clientcommands#192]
I upgrade mod to the latest version (2.4.9), and all my scripts couldn't work.

I use `/cscript run branch_mine.js` and it said "Couldn't find script 'branch_mine.js'"

![2021-02-23 20-49-25 的屏幕截图](https://user-images.githubusercontent.com/62997025/108846776-e7ca8000-7619-11eb-9b1e-750703f8745d.png)

My scripts:

![2021-02-23 20-49-38 的屏幕截图](https://user-images.githubusercontent.com/62997025/108846956-22ccb380-761a-11eb-9161-4e9457b7f69c.png)

`/cscript reload` still didn't work

**Comment by Earthcomputer** [comment]
It should be .minecraft/config, not .minecraft/versions/xxx/config
