### ISSUE TITLE
Question: Increase Ping On Purpose To Increase Fishing Probability

### ISSUE THREAD

**Issue by Sopitive** [Earthcomputer/clientcommands#196]
It seems that the biggest factor on whether or not you get the correct loot depends greatly on latency, among many other factors. If ping is constantly fluctuating, it can be difficult to actually reel in the fishing rod on the correct game tick. Would it be possible to force your ping to a specific value, such as 500ms (or higher if your internet is that bad, lower if you have better internet etc) so that the delay is always set to that fixed value most of the time. I usually do not see my ping spike above 500ms except on a few rare occasions. I am not sure if this is possible to do with fabric or if it would need to be done with a third party program/hardware. Thanks!

**Comment by Earthcomputer** [comment]
It's not high ping that's the problem, it's the fluctuating ping. With fluctuating ping, there is no single ping value you can adjust to to be sure that your packet arrives on the correct tick, so you have to make a reasonable guess, which is sort of the average of the observed pings over the last dozen or so fishing attempts (actually it's a bit more complicated than that, we have maths to account for discrete tick timesteps and outliers caused packet loss). Clientcommands already artificially sends packets further in advance in high ping conditions, and it's unlikely that you will manually be able to find a ping value more likely to give a result than what clientcommands has chosen for you. You just need to fish a few times to let clientcommands calibrate to your ping properly first.

**Comment by Sopitive** [comment]
Well that's just it, my ping can fluctuate at times between about 100ms all the way to exceed 500 and in some rare (reliatively) cases it spikes past 1000ms or higher. Averaging especially the high ping number will result in a much higher average than what I normally would deal with. For example lets say my ping fluctuates between 100ms and 500ms. If my ping at the time the packet is sent is lower or higher than the calculated average of 300ms, it would result in the fishing attempt reeling in the incorrect item, since it applies the wrong delay from the calculated average, right? I am wondering if, in addition to sending packets in advance, you could make ALL the packets consistently be sent later than what it would normally take, possibly with a configurable amount of time via a command. I hope it makes sense what I am trying to say. Basically, the best example I can think of that is somewhat similar of a concept is FPS limiting where normally your FPS would fluctuate around, but if you limit the FPS to something like 60, then it stays essentially at 60FPS and rarely ever drops below that value. If you could accomplish the same concept, but with ping instead of FPS would that work?

**Comment by Earthcomputer** [comment]
You can't just control ping like that, that's not how ping works.
