### ISSUE TITLE
/cfinditem: Caching / Bigger Area Searching

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#20]
Caching of Inventory Content.
Togglable via a temprule?
A Subcommand that toggles a mode where it opens all nearby inventories while you move arround until disabled to cache their content.
[Clear cache of inventory if it plays open animation?]
This would allow for faster searches and searching in bigger Chestrooms.

**Comment by Earthcomputer** [comment]
Implemented in 1.14
