### ISSUE TITLE
Suggsetion: counting blocks with countblocks command

### ISSUE THREAD

**Issue by m-sarabi** [Earthcomputer/clientcommands#200]
Command /ccountblocks \<block id> \<pos1> \<pos2> that counts how many of that block is in that area, and maybe /ccountentity or /ccount \<entity> that does the same things as /cfind but without filling the chat with all entity positions.

For counting blocks it might check if that area is rendered or not and only counts the blocks in a fully rendered area.

**Comment by Mhowser** [comment]
How about `/cstats` instead, that way it can include entity support down the line.

**Comment by xpple** [comment]
Also there is a typo in the name of this issue.
