### ISSUE TITLE
Suggsetion: make is killes? and block attacks?

### ISSUE THREAD

**Issue by M1ZO** [Earthcomputer/clientcommands#202]
will I was thinking if it can auto farm then why it can't auto kill animals.
lets make simple commands like "#kill pig cow chicken
and another simple function when it's pathing from place to another and there is a skeleton that shot an arrow, then it looks at it and hold the shield... it would be amazing to have this, 
also auto feed that would be the most thing that I like, but of course it dose not eats golden apple 

thinks <3

**Comment by Earthcomputer** [comment]
All of this functionality is already available with `/cscript`.
