### ISSUE TITLE
Change to Spigot causes fishing RNG manipulation to fail.

### ISSUE THREAD

**Issue by riolubruh** [Earthcomputer/clientcommands#205]
Steps to reproduce:
Make a Paper/Spigot server
try to use cfish

**Comment by Earthcomputer** [comment]
It will never work on Paper.

**Comment by mattymatty97** [comment]
Doing some testing i noticed that Paper just messes up the reel timings part, while the looting tables are still fine.
I mean that if you reel manually and you get the treasure loot, it is the loot you were searching for.

it might have been all my luck but if it was not, i'd like to see a looting_table settings for cfish to just do the recasting and then either reel manually or using a classic autofish script

**Comment by Earthcomputer** [comment]
Sorry, that's not true. Paper will throw off both the timing and the loot predictions. Maybe you are testing in a test world containing just you and the fishing bobber? Then it would work. But as soon as you add other entities it won't work anymore.

**Comment by mattymatty97** [comment]
ok then i was just luky i guess, thx for the answer
