### ISSUE TITLE
Crash on joining world with JDK 16

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Earthcomputer/clientcommands#207]
Recently updated to JDK 16. Fabric loader, minecraft, all my other mods, etc. work with JDK 16, but this mod doesn't.

[Crash Report](https://gist.github.com/DragonEggBedrockBreaking/8af1fa71433d13bfeec8f2cf62234cf4)

System/Mods/Other:
- Windows 10
- Minecraft 1.16
- ClientCommands 2.4.9 (Latest stable release, can also reproduce with latest commit)
- Fabric Loader 0.11.2
- Fabric API 0.32.0
- MultiMC 5 (0.6.11)
- AdoptOpenJDK 16 (Hotspot)

**Comment by AI-nsley69** [comment]
Still happening with graalvm [java 16](https://paste.ee/p/RhXaI)

**Comment by ghost** [comment]
Did you update client commands? in your log it shows `clientcommands: Client Commands 2.4.8` and the current version is 2.4.10

**Comment by AI-nsley69** [comment]
Okay yeah that was the issue. Should've checked that
