### ISSUE TITLE
`/cfinditem` will pause unexpectedly long for blocked shulker-boxes

### ISSUE THREAD

**Issue by Domkeykong** [Earthcomputer/clientcommands#219]
When using `/cfinditem` and there is a blocked shulker-box, with a block ontop of it, the search will pause unexpectedly long (c.a. 6sec).

**Comment by James103** [comment]
I can confirm on Client Commands release version 2.4.9 for Minecraft 1.16.5. The actual time delay is 5 seconds instead of 6 seconds.
