### ISSUE TITLE
Version 1.7.10

### ISSUE THREAD

**Issue by piecoll** [Earthcomputer/clientcommands#22]
Can you make a 1.7.10 version? Or is there a version for 1.7.10 someone has made?

**Comment by Earthcomputer** [comment]
No. If you want a 1.7.10 version you can port it yourself.

**Comment by piecoll** [comment]
Do you know of any tutorials for porting it? I'm new to this sorry.

**Comment by Earthcomputer** [comment]
You need to have a reasonable amount of Java experience, and experience with both 1.7.10 and 1.12.2 Forge modding APIs and Minecraft codebases.
