### ISSUE TITLE
`/cenchant` can desync when throwing items

### ISSUE THREAD

**Issue by Domkeykong** [Earthcomputer/clientcommands#220]
`/cenchant` can desync when item are thrown stop e.g.: opening the inventory
(tested with creative, doesn't seem work in survival) or a laggy server

**Comment by Earthcomputer** [comment]
This might have been fixed in vanilla in 1.17, so it needs retesting when that comes out.

**Comment by Earthcomputer** [comment]
Should be fixed by now.
