### ISSUE TITLE
`/csound`?

### ISSUE THREAD

**Issue by barraIhsan** [Earthcomputer/clientcommands#222]
There is 3 Parameter, `/csound play` to play a sound. `/csound stop` to stop a sound. and `/csound get` to get a current playing song

`/csound play <sound> [<source>] [<pos>] [<volume>] [<pitch>] [<minVolume>] `
`source` by default is `master`
`pos` by default is `~ ~ ~`
`volume` by default is `1`
`pitch` by default is `1`

`/csound stop [<source>] [<sound>]`
`source` by default is `*`
`sound` by default is `<all the sound from the source>`

`/csound get [<source>]`
`source by default is *`

**Comment by haykam821** [comment]
See #175 

`/csound get` does not exist but that is the case with the server-side equivalent as well.

**Comment by barraIhsan** [comment]
oh ok, but i think i prefer `/csound play` and `/csound stop` (to make less command?)
