### ISSUE TITLE
Bring `/cbook` back?

### ISSUE THREAD

**Issue by barraIhsan** [Earthcomputer/clientcommands#223]
yes, i know the bug has been fixed in vanilla. But I found that there is another dupe using the book. 
So first, we gonna disconnect first (save player inventory), then reconnect. After that, we gonna place the item that want to duped in the chest / barrel / container (make sure its the same chunk) and write stuff in book and quil (65546 byte i think), and then after that the server kicked me out with an error `io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: encoded string too long: 65546 bytes`. The server doesn't save the player inventory, and there is `Failed to save player data for <playername>`. After that show up in log, you must to reconnect. And it duped because the player inventory wasn't saved, but the container is saved
Video that I found : https://www.youtube.com/watch?v=M_Y-IyG5rk4&t=0s (It patched in paper I think)

**Comment by xpple** [comment]
Now I’m not sure about this, so Earthcomputer correct me if I’m wrong.
`/cbook` was never meant for duping. It was meant for creating “save-states”. Earthcomputer purposely removed the command because it was only being used for malicious intents (book banning). With this (relatively new) dupe, nothing changed towards the uses of cbook

**Comment by Vonr** [comment]
yeah clientcommands isnt a cheat client. make it yourself if you want one

**Comment by barraIhsan** [comment]
> Now I’m not sure about this, so Earthcomputer correct me if I’m wrong.
> `/cbook` was never meant for duping. It was meant for creating “save-states”. Earthcomputer purposely removed the command because it was only being used for malicious intents (book banning). With this (relatively new) dupe, nothing changed towards the uses of cbook

this is also save-states inventory maybe?

**Comment by barraIhsan** [comment]
ok then lol
