### ISSUE TITLE
[QUESTION] Does this do anything on a server?

### ISSUE THREAD

**Issue by srnyx** [Earthcomputer/clientcommands#224]
Just curious if this does anything server-side or not.

**Comment by xpple** [comment]
What do you mean with "doing anything"?

**Comment by srnyx** [comment]
> What do you mean with "doing anything"?

Like, does it add any extra support for commands or just improve the mod in any way?
Or does it just not even load/work when put onto a server?

**Comment by Earthcomputer** [comment]
Everything in this mod works in multiplayer, at least on vanilla servers, yes.
