### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by srnyx** [Earthcomputer/clientcommands#225]
This doesn't happen with any sort of command, it just happens right when I log in.
Removing clientcommands fixes it so I'm sure it's clientcommands causing it.
Here's my modpack: https://simpearth.xyz/modpack

![img](https://cdn.tixte.com/file/tixtehost/uploads/max-is.an-idiot.xyz/kn26dsaou09.png)
![img](https://cdn.tixte.com/file/tixtehost/uploads/img.srnyx.xyz/kn26hd5gl09.png)
_The blocks glitching out are ice._

**Comment by Earthcomputer** [comment]
What the heck, why does that modpack contain optifine *and* sodium at the same time? This is not clientcommands

**Comment by srnyx** [comment]
> What the heck, why does that modpack contain optifine _and_ sodium at the same time? This is not clientcommands

It doesn't lol
It says "Incompatible" not "Includes"
![img](https://cdn.tixte.com/file/tixtehost/uploads/img.srnyx.xyz/kn4s4fwic09.png)
_The latest version of the modpack hasn't been approved on CurseForge yet, but it includes Indium and Sodium._

**Comment by Earthcomputer** [comment]
clientcommands doesn't touch block rendering so it's not that.

**Comment by srnyx** [comment]
> clientcommands doesn't touch block rendering so it's not that.

What could be causing it then? It never happens without clientcommands, only happens with it.
Want me to send you my logs with clientcommands and my logs without clientcommands?

**Comment by Earthcomputer** [comment]
Don't ask me what's causing it but it's not clientcommands. Not my responsibility to fix other mods
