### ISSUE TITLE
[Suggestion] `/ckits`

### ISSUE THREAD

**Issue by barraIhsan** [Earthcomputer/clientcommands#226]
So this is just like `/cgive`, its only accessible in creative.
So sometimes, for example when we making redstone machine, the saved toolbar just not enough (only 9 items). So this command can delete, load, and save inventory

Syntax :
`/cinventory (load|save|delete) <file name (without .txt)>`
and then maybe store the inventory in `.minecraft/config/clientcommands/inventory/` with txt format?
So inside `.minecraft/config/clientcommands/inventory/<file name>.txt` will be
```
<armor.helmet>
<armor.chestplate>
<armor.leggings>
<armor.boots>

<weapon.offhand>

<inventory.0>
....
<inventory.36>

<hotbar.0>
....
<hotbar.8>
```

**Comment by Mhowser** [comment]
JSON would be a better format than plaintext. Great idea tho.

**Comment by barraIhsan** [comment]
> JSON would be a better format than plaintext. Great idea tho.

Yeah, but when we want to edit them (open the config file), sometimes its frustrated that you have to like escape quote, etc.

**Comment by Earthcomputer** [comment]
Given that you can save it with a command, might as well just save it in NBT format.

**Comment by xpple** [comment]
> Given that you can save it with a command, might as well just save it in NBT format.

On it

**Comment by barraIhsan** [comment]
> Given that you can save it with a command, might as well just save it in NBT format.

Oh, I think nbt file size is also small if I'm not mistaken?

**Comment by xpple** [comment]
> > Given that you can save it with a command, might as well just save it in NBT format.
> 
> Oh, I think nbt file size is also small if I'm not mistaken?

I’m currently working on it and it works fine actually. As suggested by Earthcomputer I will be storing all the kits in one `.dat` file. I may also compress it if needed

**Comment by barraIhsan** [comment]
oh cool!
