### ISSUE TITLE
Unable to launch: unsatisfied dependencies

### ISSUE THREAD

**Issue by foaw** [Earthcomputer/clientcommands#23]
[corrected]

**Comment by hube12** [comment]
you need to install the correct fabric loader which is mapping 1.14 build 1 and loader 0.4.2 b132 https://fabricmc.net/download/multimc?yarn=1.14%2Bbuild.1&loader=0.4.2%2Bbuild.132

**Comment by hube12** [comment]
you have mappings for 1.14 build 3

**Comment by xdelsy** [comment]
Still doesn't work... [x](https://paste.ee/p/X34MW)

**Comment by xdelsy** [comment]
I've not installed FabricAPI ._.
