### ISSUE TITLE
Custom creative tabs

### ISSUE THREAD

**Issue by barraIhsan** [Earthcomputer/clientcommands#235]
So first, **I don't know if it's possible or not.** 
And second, yes, I can't think of a better name

### Usage 
```sh
/citem add item <item|slot> <id> <categoryName>
```
```sh
/citem remove item <id> <category>
```
`item` is mean the [item_stack](https://minecraft.fandom.com/wiki/Argument_types#minecraft:item_stack)
`category` is mean the category name, can be vanilla/default, or custom (see below)

```sh
/citem add category <categoryName> <displayName>  <icon|slot>
```
```sh
/citem remove category <categoryName>
```
`displayName` is mean the actual name for it, support [Raw JSON Format](https://minecraft.fandom.com/wiki/Raw_JSON_text_format)
`icon` is mean the icon for category
![image](https://user-images.githubusercontent.com/57800056/114654476-74d5af80-9d14-11eb-9564-423f03707929.png)
^ the icon is `lava_bucket`
`slot` is mean the [item_slot](https://minecraft.fandom.com/wiki/Argument_types#minecraft:item_slot)
```sh
/citem list <item|category>
```

#### Items
For adding it, run this command (for example)
`/citem add item debug_stick 1 misc`
It will add `debug_stick` to the `misc` category
we can also add `air`, we cannot take it, the air is just for organizing item
![image](https://user-images.githubusercontent.com/57800056/114654111-a9953700-9d13-11eb-8d1a-ae4f84b66d3d.png)
For example, the image above is `debug_stick`, `air`, `debug_stick`

Then, for removing it, run this command (for example)
`/citem remove item 1 misc`
It will delete the name of `1` (which in this case, is that debug stick) from the `misc` category. (And each category have a different name, so you can use the name `1` again in another category)

#### Category
For adding it, run this command (for example)
`/citem add category commandsOnly {"text":"Commands Only","bold":true} command_block{Enchantments:[{}]}`
It will add a category called **Commands Only** and the logo is command block (but shiny, because why not?)
And items can put into this category (eg. `/citem add debug_stick 2 commandsOnly`)

For removing it, run this command (for example)
`/citem remove category commandsOnly`
And basically, it will remove the categoryName of `commandsOnly` (which in this case, is that **Commands Only**)

#### List
For listing them, run this command (for example)
`/citem list item`
then, it will list out, all the item that we add

Oh also (I don't know if it's possible or not), can you add a search bar for each custom tabs?
Why?
Because for some reason custom added items to items tabs don't appear in regular search

**Comment by Earthcomputer** [comment]
It's probably possible to do this, although I'd call it `citemgroup` or `ccreativetab` instead of `citem`

**Comment by xpple** [comment]
Very interesting suggestion. I'll play around with it a bit

**Comment by barraIhsan** [comment]
> It's probably possible to do this, although I'd call it `citemgroup` or `ccreativetab` instead of `citem`

Yes, I've been thinking for splitting them, but I cant think of better name, that is a better name!

**Comment by xpple** [comment]
> > It's probably possible to do this, although I'd call it `citemgroup` or `ccreativetab` instead of `citem`
> 
> Yes, I've been thinking for splitting them, but I cant think of better name, that is a better name!

90% done

**Comment by barraIhsan** [comment]
what?? i think its not possible because I cant find mod that save item in item group (and also make the item group)

**Comment by xpple** [comment]
Say hello to clientcommands!

**Comment by barraIhsan** [comment]
Ah yes, literally the description of this mod (in github) is "How far can a Minecraft client be taken?" lol

**Comment by Earthcomputer** [comment]
A mod can do anything your computer can do, so of course this is possible. The real question when deciding to implement features for mods is not a question of whether it's possible, more a question of whether it's cost-effective to do so. Aka which features have the highest reward compared to the time you spend implementing them. Maintenance is also something to be considered too, aka how much of a pain will a feature be to update to future Minecraft versions, or will the feature become redundant in the next Minecraft update anyway.

**Comment by wagyourtail** [comment]
for compatibility's sake (ab)use fabric api. they have it merged https://github.com/FabricMC/fabric/pull/44

**Comment by xpple** [comment]
I’m using that.

**Comment by xpple** [comment]
Also note how the removing part of these item groups was never merged (nor planned to code). I feel like this can only be done internally (within Fabric) or externally with a fuck lot of pain.

Simple removing the item group from `ItemGroup.GROUPS` won’t cut it. That aside the entire command is done...

**Comment by barraIhsan** [comment]
> A mod can do anything your computer can do, so of course this is possible. The real question when deciding to implement features for mods is not a question of whether it's possible, more a question of whether it's cost-effective to do so. Aka which features have the highest reward compared to the time you spend implementing them. Maintenance is also something to be considered too, aka how much of a pain will a feature be to update to future Minecraft versions, or will the feature become redundant in the next Minecraft update anyway.

ahhh... I understand now
