### ISSUE TITLE
[Suggestion] UUID Autocomplete when looking at entity

### ISSUE THREAD

**Issue by barraIhsan** [Earthcomputer/clientcommands#241]
So, in vanilla when you look at an entity, then there is their UUID in the autocomplete (for example /data get entity)
![image](https://user-images.githubusercontent.com/57800056/116705286-91e9ce00-a9f6-11eb-88de-a7e20a867b79.png)
But, in client commands, it doesn't happen (for example /cgetdata entity )
![image](https://user-images.githubusercontent.com/57800056/116705252-85fe0c00-a9f6-11eb-9aed-02dd054bd262.png)
Same position, same entity.

Yes, it already [said](https://discord.com/channels/703363189081112647/703363189081112650/809386447282241576) that it gonna add into client command, but its forgotten

**Comment by xpple** [comment]
Lemme have a look
