### ISSUE TITLE
You can move item while in `ckit preview`

### ISSUE THREAD

**Issue by barraIhsan** [Earthcomputer/clientcommands#245]
So, when you run `ckit preview <name>`, then it will open up the preview inventory GUI.
But if you have something in your inventory, you can move it while in preview mode.
If it's WAI, we should not move the item in preview mode.

https://user-images.githubusercontent.com/57800056/116779591-666fed80-aaa1-11eb-8b27-d18f48c2a5a6.mp4

**Comment by xpple** [comment]
I really wonder why this happens. I’ll have a look.

**Comment by xpple** [comment]
Fixed it, will PR later.
