### ISSUE TITLE
[Suggestion] Replace feature on ghostblock fill command.

### ISSUE THREAD

**Issue by AliahX** [Earthcomputer/clientcommands#247]
Java fill command is like this:
```
fill <from> <to> <block> [destroy|hollow|keep|outline|replace]
fill <from> <to> <block> replace [<filter>]
```
I think ghostblock fill should have those features as well:

```
cghostblock fill <from> <to> <block> [destroy|hollow|keep|outline|replace]
cghostblock fill <from> <to> <block> replace [<filter>]
```

**Comment by OneYellowLemon** [comment]
What is this issue for? "Replace feature on ghostblock fill command" is not enough information.

**Comment by 0f-0b** [comment]
Did you mean `cghostblock fill <from> <to> <block> replace <filter>`?

**Comment by xpple** [comment]
What would that even do?

**Comment by Earthcomputer** [comment]
Same as `/fill ... replace ...` presumably

**Comment by xpple** [comment]
I must be stupid cause I have never known that existed. Let me check it out.

**Comment by xpple** [comment]
@Earthcomputer enhancement or no?

**Comment by AliahX** [comment]
Java fill command is like this:
```
fill <from> <to> <block> [destroy|hollow|keep|outline|replace]
fill <from> <to> <block> replace [<filter>]
```
I think ghostblock fill should have those features as well:

```
cghostblock fill <from> <to> <block> [destroy|hollow|keep|outline|replace]
cghostblock fill <from> <to> <block> replace [<filter>]
```

**Comment by Earthcomputer** [comment]
@TexRexTex thanks for clarifying, you should have clarified that in your original post, rather than leaving us guessing.

**Comment by OneYellowLemon** [comment]
Any update on this?

**Comment by UnJust1ce** [comment]
It shouldn't be that hard right?? I used the minecraft code as a reference and made the syntax in a fork pretty easily.

**Comment by RealRTTV** [comment]
it's been implemented now hasn't it?
