### ISSUE TITLE
All commands unknown

### ISSUE THREAD

**Issue by SpiffLasagna** [Earthcomputer/clientcommands#25]
I think I've downloaded the client somewhat correctly. Commands show up but when I type any command, I get "Unknown command".

**Comment by Penzillius** [comment]
You might wanna try adding things after that, for example if you just type "/cbook' it doesnt work, but "/cbook random" does.

**Comment by Earthcomputer** [comment]
@SpiffLasagna let me know if @Penzillius' suggestion works. If so then it's a vanilla bug and happens to vanilla commands too. Feel free to upvote https://bugs.mojang.com/browse/MC-121634

**Comment by Earthcomputer** [comment]
Closing because no response in a while. If it's still an issue reply and I can reopen.
