### ISSUE TITLE
Forge or Fabric loader

### ISSUE THREAD

**Issue by music-cat-bread** [Earthcomputer/clientcommands#256]
Hi.
I am not sure what I need to use to load this mod.
Should I use Forge or Fabric loader?
(Sorry for bad English)

**Comment by barraIhsan** [comment]
Fabric Loader, also you have to read the README.md first. There is [Installation](https://github.com/Earthcomputer/clientcommands/blob/fabric/README.md#Installation) on the readme

**Comment by music-cat-bread** [comment]
Thanks

**Comment by barraIhsan** [comment]
![image](https://user-images.githubusercontent.com/57800056/117782982-55c33280-b26c-11eb-8da9-9269c17c9b35.png)
Now, close it after you done with it.
Also if you have any question, join the [Discord](https://discord.gg/Jg7Bun7)
