### ISSUE TITLE
Player Name History Command

### ISSUE THREAD

**Issue by RubiiJet** [Earthcomputer/clientcommands#257]
I would like a QOL command that will list the name history of someone in chat (privately).
The command may be /cnamehistory or similar. The ability to be able to tab through online players would be appreciated.

**Comment by xpple** [comment]
I wish I had time to implement this :(.

**Comment by xpple** [comment]
The code for this will be much cleaner with the availability of Java 16 and its `HttpRequest` class. Maybe it’s an idea to wait for that? ~~So that I can implement it.~~ 😂 /s

**Comment by xpple** [comment]
On it.
