### ISSUE TITLE
[Feature Suggestion] `cghostblock remove`

### ISSUE THREAD

**Issue by barraIhsan** [Earthcomputer/clientcommands#261]
So simple there is 2 syntax
```mcfunction
cghostblock remove all
```
This is to remove all ghost block

```mcfunction
cghostblock remove <x> <y> <z> [<x2>] [<y2>] [<z2>]
```
This is to remove ghostblock in certain area you can do it with 1 block or 2 block (area)

**Comment by Earthcomputer** [comment]
Why not just relog?

**Comment by barraIhsan** [comment]
Well, we can remove ghost block either dying or relog. But I think this is the easier way

**Comment by Earthcomputer** [comment]
There is a `/crelog` command btw

**Comment by MrAn0nym** [comment]
> Why not just relog?

Sometimes you don't want a mobs to despawn and I'm sure there can be other situations when you don't want to disconnect. As long as it is not too much work to implement it should be added (in my opinion)

**Comment by Earthcomputer** [comment]
Not that simple I'm afraid.

![image](https://user-images.githubusercontent.com/13084089/118537407-d12d5400-b744-11eb-8c2d-28113ab0ac9c.png)

**Comment by Vonr** [comment]
how about adding the positions of ghost blocks created by clientcommands to a hashmap then removing those ghsot blocks with the command if their positions are in the hashmap? it wouldnt remove ghost bpocks not generated by cc but should work well enough

**Comment by barraIhsan** [comment]
Well, that's work but I'm not sure if you can remove/add ghost block to unloaded chunk...

**Comment by Earthcomputer** [comment]
That all sounds very simple until you remember that pistons exist :P

**Comment by barraIhsan** [comment]
Can piston push ghost block?

**Comment by Earthcomputer** [comment]
Yes

**Comment by barraIhsan** [comment]
Thats make it a lot harder. What about remove it in radius? Sometimes when you are mining with efficiency 5 and haste 2. Its create ghost block

**Comment by RaphiMC** [comment]
One kinda crappy solution would be to spam many block place packets around the player when the command is entered. As you can see here (in the last 2 lines of code), the normal vanilla server would always send the correct block on that position back which would remove any ghost block the client previously had there. This behaviour is not affected by range, the only thing is, that the client would need to have an empty slot, else it would actually place blocks.
![grafik](https://user-images.githubusercontent.com/50594595/118647494-ae04b200-b7e1-11eb-8c1e-00f2d5991f3c.png)

**Comment by Earthcomputer** [comment]
There is a better solution for close range that is implemented in 1.12 clientcommands, and that's to send an abort digging packet for the location, which causes the server to send the block at that position. I don't know if that works anymore.

**Comment by User670** [comment]
As far as my knowledge of glost blocks go, right clicking the ghost block removes it.

**Comment by barraIhsan** [comment]
> As far as my knowledge of glost blocks go, right clicking the ghost block removes it.

Yes, also if you right click with block. The Ghost Block will be replaced by the block
Or, I think its the same as left click

**Comment by Mhowser** [comment]
>One kinda crappy solution would be to spam many block place packets around the player when the command is entered.

This will potentially trigger Anti-cheat plugins

**Comment by RaphiMC** [comment]
> > One kinda crappy solution would be to spam many block place packets around the player when the command is entered.
> 
> This will potentially trigger Anti-cheat plugins

Every ghostblock removal feature will trigger anticheats. Even if you don't click through blocks, clicking on a ghost block is the same for anticheats as it doesn't know that theres a ghost block

**Comment by Earthcomputer** [comment]
Closing as not realistic to implement in a way that isn't badly flawed
