### ISSUE TITLE
fisher bobber configuration incorrect

### ISSUE THREAD

**Issue by Fel1xDev** [Earthcomputer/clientcommands#262]
i was trying to manipulate fishing but it keeps saying
"fisher bobber configuration is incorrect"
what does it mean and how can i fix it?

**Comment by barraIhsan** [comment]
You have to put lily pad and try get the bobber under it. [There is a video about that](https://www.youtube.com/watch?v=-kJoNBWDBn0) and please ask in the [discord](https://discord.gg/Jg7Bun7) server for future help!
