### ISSUE TITLE
cglow block rendering failing at a far away distance

### ISSUE THREAD

**Issue by RealRTTV** [Earthcomputer/clientcommands#268]
going millions of blocks out with a /cglow on a block will cause the sides to deform and not align to the blocks position. I think this is to do with weird floating point math or whatever and it occurs with tracing stuff far away just wondering if there's an actual way to fix it

**Comment by xpple** [comment]
I asked about this in the Discord server as it was an issue for my own mod as well; the proposed solution was to use raw OpenGL method calls.

**Comment by Earthcomputer** [comment]
I think the solution is to draw everything in view space

**Comment by xpple** [comment]
Why don't we use `WorldRenderer#drawBox` to render the outline?

**Comment by xpple** [comment]
@Earthcomputer should I implement [this](https://github.com/xpple/SeedMapper/commit/16af68c163c47fedc9b9751616f789a3d26dcb90) here?
