### ISSUE TITLE
Render issue with shaders

### ISSUE THREAD

**Issue by SpacEagle17** [Earthcomputer/clientcommands#269]
Hi, I have noticed that this mod breaks optifine shaders. I have tried it with complementary shaders and the underwater colour is broken see this [video](https://user-images.githubusercontent.com/46494907/120507339-02558780-c3c7-11eb-8d91-613b5e2c76f7.mp4)

In sildurs vibrant it is even more broken as you can see in this [video](
https://user-images.githubusercontent.com/46494907/120507794-69733c00-c3c7-11eb-862b-089fe5c94eda.mp4)
These are the only mods I had on at that time:
![image](https://user-images.githubusercontent.com/46494907/120507943-8c9deb80-c3c7-11eb-9a71-77c3e93b0406.png)
Any ideas why this mod would break shaders?
Have a nice day!

**Comment by Earthcomputer** [comment]
No I have no clue, clientcommands barely touches rendering. OptiFine is so fragile it's awful. My stance on OptiFine related issues is that you should report them to the optifabric repo instead.

**Comment by SpacEagle17** [comment]
Ok, let's hope it can be fixed with iris

**Comment by SpacEagle17** [comment]
Update: 
Here is the optifabric bug report and they said that it might be fixable
https://github.com/Chocohead/OptiFabric/issues/228#issuecomment-853515479

They said that the issue comes from [this clear call](https://github.com/Earthcomputer/clientcommands/blob/fabric/src/main/java/net/earthcomputer/clientcommands/mixin/MixinGameRenderer.java#L30)

**Comment by coderbot16** [comment]
Just saw this, obliterating the depth buffer like that will definitely cause problems for shaders since they need the depth buffer data to accomplish a lot of their effects. In fact, I wonder if it causes problems for fabulous graphics too, since it uses shaders which access a few depth buffers? Render layers with depth testing disabled will probably cause less issues here, if that's possible.

**Comment by SpacEagle17** [comment]
Maybe this issue should be reopened?

**Comment by coderbot16** [comment]
Interestingly enough though, I thought about it and remembered hand rendering is after WorldRenderer has finished. I don't think that this will cause problems with Iris as a result, but perhaps OptiFine is rendering the final stage of shaders a lot later than Iris does. In any case, it's probably still a good idea to avoid clearing the depth buffer for custom rendering.

**Comment by Earthcomputer** [comment]
The goal is to simply be able to render lines always above blocks. I'm not the best at rendering, if someone can suggest an alternative way of doing that I'll happily change it

**Comment by coderbot16** [comment]
The correct way is through disabling the depth test. It looks like you already do this, but it seems likely that the RenderLayer system could be overriding that.

**Comment by Earthcomputer** [comment]
Reopening as I'd like to fix it, as much as I despise optifine, it may cause incompatibilities with other mods too

**Comment by ImUrX** [comment]
why not check how carpet does it? https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/script/utils/ShapesRenderer.java i think it was
