### ISSUE TITLE
no version for 1.13.2

### ISSUE THREAD

**Issue by REDPANDAUwU** [Earthcomputer/clientcommands#27]
please make a version for 1.13.X you went from 1.12.X to 1.14 please dont skip 1.13.X

**Comment by Platypus3112** [comment]
From the latest release: "I also skipped 1.13 since it was getting infeasible to maintain a version for Forge and Rift was only a temporary mod loader."
Also, this is more of a request than an issue.

**Comment by Earthcomputer** [comment]
Yep. If you want a 1.13.x version please make it yourself, I don't have the time to support 1.13.x.
