### ISSUE TITLE
Add entity_tags to selector in cglow command

### ISSUE THREAD

**Issue by Shroototem** [Earthcomputer/clientcommands#270]
For example:
`/cglow --keep-searching-entities entities @e[type=#minecraft:hostile] 1 color red`
`/cglow --keep-searching-entities entities @e[type=#minecraft:skeletons] 1 color red`

None of these work in the current version of the mod.

This is just a working example:
`/cglow --keep-searching-entities entities @e[type=minecraft:skeleton] 1 color red`

**Comment by xpple** [comment]
On it.

**Comment by Shroototem** [comment]
Thank you! ♥

**Comment by xpple** [comment]
There ya go!
