### ISSUE TITLE
Can I have clook when clicking on coordinates in cfindblock?

### ISSUE THREAD

**Issue by User670** [Earthcomputer/clientcommands#275]
I'd like an way to have clook instead of, or in addition to, cglow when clicking on a block coordinate in cfindblock, like how some old versions used to do :-(

**Comment by barraIhsan** [comment]
Agree! Or better option will be
[Look] [Glow]
at the end of the message. So you can have an option

**Comment by L0um15** [comment]
I'll try to make PR tommorow.

**Comment by L0um15** [comment]
Can't sleep.
Look by default, glow next to it.
![image](https://user-images.githubusercontent.com/44427021/121094593-2eba3b00-c7ef-11eb-9aae-4bd1c84adee6.png)

**Comment by xpple** [comment]
Nice! Would it be possible to look at the block without executing the `clook` command?

**Comment by L0um15** [comment]
> Nice! Would it be possible to look at the block without executing the `clook` command?

I wanted to do that, but then i saw `getLookCoordsTextComponent` inside `ClientCommandManager.class`
