### ISSUE TITLE
cbook missing

### ISSUE THREAD

**Issue by StereoMadnessss** [Earthcomputer/clientcommands#277]
I liked cbook and it seems to have been removed. Could it come back?

**Comment by haykam821** [comment]
Book commands only have non-cheating uses in older versions of Minecraft. As such, using [Multiconnect](https://github.com/Earthcomputer/multiconnect) to join an older Minecraft server will allow you to use the command.

The clientcommands project is not meant to be used for cheating, so book commands in the context of newer versions of Minecraft are out of scope for the project.
