### ISSUE TITLE
Suggestion: Add the `ctitle` command

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#282]
Currently, there is no way (that I know of) to display title text (in the title, subtitle, or action bar slots) completely client side. Other mods do display title text client side, which shows that it can be done. Such title text could be used to mark milestones (such as "Congratulations!" "You reached day 100!") or other events. To add to this, a `ctitle` command could be added to the mod, which works exactly the same as `/title`, but has no `<targets>` argument (which always defaults to yourself).

**Comment by xpple** [comment]
Waiting for an enchancement tag to get started.

**Comment by xpple** [comment]
That was quick 🤣.
