### ISSUE TITLE
Player's horizontal rotation is unbounded, causing it to become jittery at high values

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#284]
As of Minecraft 1.17, it is possible to rotate so far left or right that you start to notice precision losses in your horizontal rotation. Eventually, you may not be able to rotate at all on the client side if you rotate too far to the left or right. This is likely a vanilla bug ([MC-131146](https://bugs.mojang.com/browse/MC-131146)), but it is more easily seen if you use Client Commands and do the following:
1. Set your mouse at a high sensitivity rating, then open the game (and a world) and move your mouse far to the left or right.
2. Without moving your mouse too much, run `/cgetdata entity @s Rotation`. Notice that the horizontal rotation is outside the bounds of [-180, 180).
3. Run `/clook angles 9000000 0`.
4. Try to move your mouse a small amount. Notice that your view does not rotate as at these values, your rotation can only take on integer values in degrees.

**Comment by Earthcomputer** [comment]
It's out of the scope of clientcommands to fix vanilla bugs
