### ISSUE TITLE
.cbook doesent work

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#288]
i type in chat nothing happens

**Comment by barraIhsan** [comment]
`/cbook` is removed at 1.15, [this release](https://github.com/Earthcomputer/clientcommands/releases/tag/v2.4.6)

**Comment by ghost** [comment]
> `/cbook` is removed at 1.15, [this release](https://github.com/Earthcomputer/clientcommands/releases/tag/v2.4.6)

fuuuuuuuuuuuuuuuu ok thx

**Comment by ghost** [comment]
> `/cbook` is removed at 1.15, [this release](https://github.com/Earthcomputer/clientcommands/releases/tag/v2.4.6)

is there an alternative

**Comment by barraIhsan** [comment]
IDK if I can discuss it here tho. ~~But wurst have .dupe~~

**Comment by ghost** [comment]
@barraIhsan it works only on vanilla servers :(

**Comment by Earthcomputer** [comment]
clientcommands isn't a hacked client

**Comment by ghost** [comment]
> clientcommands isn't a hacked client

I never said it was. I was just asking why it didnt work.

**Comment by Earthcomputer** [comment]
It only works on servers where there are non-malicious use cases
