### ISSUE TITLE
/cglow block doesn't render block outline on AMD GPUs

### ISSUE THREAD

**Issue by manyrandomthings** [Earthcomputer/clientcommands#289]
Fancy graphics vs Fabulous graphics, no other mods used
![fancy_fabulous](https://user-images.githubusercontent.com/42223559/124364997-3cf34f80-dc13-11eb-9c53-dabbaefd8cb5.png)

**Comment by Earthcomputer** [comment]
Does this still happen on the latest version?

**Comment by manyrandomthings** [comment]
Just tested versions 1.18.2 though 1.19.4, everything up to 1.19.3 works just fine with both fancy and fabulous graphics, but in 1.19.4 it doesn't render the outline at all for any graphics setting.

**Comment by Earthcomputer** [comment]
Did you try the latest version on 1.19.4? Earlier 1.19.4 versions had a bug where they didn't render it.

**Comment by manyrandomthings** [comment]
Yep, not getting any outlines with version 2.7.11

**Comment by Earthcomputer** [comment]
What graphics drivers are you using?

**Comment by manyrandomthings** [comment]
AMD RX 6750 XT with driver version 22.40.51.05

**Comment by manyrandomthings** [comment]
Just tested on an old computer that has an nvidia gpu and it can render the outline just fine, so it seems to just be an issue with amd gpus as far as I can tell

**Comment by Earthcomputer** [comment]
@manyrandomthings can you see if [this version](https://github.com/Earthcomputer/clientcommands/suites/12957953490/artifacts/700657227) works on AMD?

**Comment by manyrandomthings** [comment]
Still not rendering anything

**Comment by Earthcomputer** [comment]
Do you have any other mods installed by any chance?

**Comment by manyrandomthings** [comment]
Nope, only using client commands and fabric api

**Comment by Earthcomputer** [comment]
Do you think you'd be able to get a snapshot with renderdoc?

**Comment by manyrandomthings** [comment]
Trying to figure out how to use renderdoc but I can't figure out how to save captures, is there a guide anywhere?

also I've joined your discord, it should be much easier to continue discussing there

**Comment by zeichenreihe** [comment]
GPU in use:
```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics G7 (rev 07)
```
Mods in use: `clientcommands-2.7.8.jar`, `fabric-api-0.73.2+1.19.3.jar`
Additional mods `sodium-fabric-mc1.19.3-0.4.9+build.23.jar`

- no sodium; with fancy graphics ![2023-05-17_16 47 23](https://github.com/Earthcomputer/clientcommands/assets/67289119/0c87e187-4514-4f96-9475-aa854a0488bf)
- no sodium; with fabulous graphics ![2023-05-17_16 47 40](https://github.com/Earthcomputer/clientcommands/assets/67289119/9631ebb6-d70a-4c0d-981a-b0c15dcc1ea4)

- with sodium; with fany graphics ![2023-05-17_16 49 45](https://github.com/Earthcomputer/clientcommands/assets/67289119/e9aaa29c-75d9-4992-b6a9-f326ed4f8109)
- with sodium; with fabulous graphics ![2023-05-17_16 49 29](https://github.com/Earthcomputer/clientcommands/assets/67289119/f068182e-486f-43b1-b61c-8cf6423f3f33)

as you can see: the box renders fine in any configuration

**Comment by Earthcomputer** [comment]
https://github.com/Earthcomputer/clientcommands/commit/99c18759b01b04bc07d39edbad7158d3f1c0b954
