### ISSUE TITLE
No option for Sharpnes V

### ISSUE THREAD

**Issue by music-cat-bread** [Earthcomputer/clientcommands#292]
**Minecraft version:** 1.16.5
**clientcommands version:** 2.4.10

**Problem:**
There is no option to manipulate enchating table ot foshing rod to get Sharpness V enchantment, Only IV.

**Comment by DJtheRedstoner** [comment]
It is not possible to get sharpness 5 while fishing, therefore it doesn't show as an option.

**Comment by music-cat-bread** [comment]
But is is possible to get it from enchating table?

**Comment by OneYellowLemon** [comment]
Only on iron axes iirc.

**Comment by music-cat-bread** [comment]
But why?

**Comment by OneYellowLemon** [comment]
Ask the Mojang developers who made it that way ¯\_(ツ)_/¯. Probably balancing.

**Comment by music-cat-bread** [comment]
Ok
