### ISSUE TITLE
/cfish manipulation won't allow me to select specific enchants on books/rods/bows on multiplayer

### ISSUE THREAD

**Issue by Pyrolaxian** [Earthcomputer/clientcommands#295]
Before starting: The server is a realm and is unmodded and doesn't have spigot nor paper and is completely vanilla.

The manipulation works when just selecting enchanted_book or book, but whenever i add "with minecraft:enchanthere" + either 1,2,3,4 or * it will not ever throw the cast and will just repeatedly throw it (i tested for about 10mins) works on singleplayer just fine but on realms/multiplayer it does not

1.17.1

**Comment by Earthcomputer** [comment]
Please make sure you have satisfied the "open water" condition for fishing as specified on the Minecraft wiki. If you think you have, please post a screenshot of your configuration on multiplayer.

**Comment by Pyrolaxian** [comment]
yeah, this was the issue! TY :D
