### ISSUE TITLE
[BUG]can't work well with optifabric and optifine

### ISSUE THREAD

**Issue by AbrasiveBoar902** [Earthcomputer/clientcommands#298]
If I use clientcommands with optifine+optifabric and enable shader packs,all block will be black

**Comment by AbrasiveBoar902** [comment]
I use Sildurs Vibrant Shaders Lite,clientcomands 2.5.3,optifine HD U G9 pre30,optifabric 1.11.18

**Comment by barraIhsan** [comment]
Duplicate of #269
