### ISSUE TITLE
1.14.2 does not work

### ISSUE THREAD

**Issue by hinley2007** [Earthcomputer/clientcommands#299]
client command in 1.14.2 does not work, when i have fabric api on, the game will crash, when i don't have it on, it says u must have any version of fabric, and i make sure that my fabric api, fabric version are all in 1.14.2 which is the correct version and the fabric installer was the newest

**Comment by MrAn0nym** [comment]
Older versions are not supported afaik

**Comment by Earthcomputer** [comment]
1.14.2 is not supported
