### ISSUE TITLE
Picking up item you are trying to find.

### ISSUE THREAD

**Issue by Platypus3112** [Earthcomputer/clientcommands#30]
When you execute _/cfinditem [item]_ when you already have the item in your inventory, it returns 

> You already have the item in your inventory dummy!

However, when you pick the item up **after** you typed _/cfinditem [item]_, it sees it in your inventory, and thus says the item is in each inventory you check.

This is in 1.12

Sidenote, I heard in 1.14 it no longer sees item in your own inventory. Is this also in the 1.12 version? Same for checking inventories of shulker boxes that are in another inventory.

**Comment by Platypus3112** [comment]
idk did i do proper issue report or wat

**Comment by Jan3kk** [comment]
m8 can u tell me where is my .jar file ? i dont know where is build/libs

**Comment by Platypus3112** [comment]
> m8 can u tell me where is my .jar file ? i dont know where is build/libs

u mean liek https://github.com/Earthcomputer/clientcommands/releases ?

**Comment by Earthcomputer** [comment]
@Jan3kk if you are still having problems please create a new issue, rather than hijacking an unrelated one ;)

**Comment by leumasme** [comment]
The 1.12 and other versions were not updated in 6 Months, do you plan on ever porting the new cool features from 1.14 into the older versions @Earthcomputer ?

**Comment by Anunayj** [comment]
Another Hijack... Though Would love the features in 1.12 :P

**Comment by leumasme** [comment]
its not really a hijack as the issue is that a feature implemented into 1.14 is missing in the 1.12 version @Platypus3112

**Comment by Earthcomputer** [comment]
1.12 is not supported anymore, sorry.
