### ISSUE TITLE
Game crashes when I install mod in 1.14.1 also can this be used in multiplayer?

### ISSUE THREAD

**Issue by ItsAlaNo** [Earthcomputer/clientcommands#31]
By multiplayer i mean some defult vinilla survival world

**Comment by Mhowser** [comment]
If you want help you need to provide a crash log.

**Comment by Platypus3112** [comment]
Yes you can use clientcommands in singleplayer and multiplayer. I believe some of the features won't work on multiplayer though, for example getting the player seed without cracking it.

**Comment by Earthcomputer** [comment]
You can use clientcommands in both singleplayer and multiplayer. There is no 1.14.1 version, although I just released a version for 1.14.2.
