### ISSUE TITLE
Rendering bug around Immersive Portal in 1.17.1

### ISSUE THREAD

**Issue by Kouchya** [Earthcomputer/clientcommands#313]
I was testing this mod in a 1.17.1 single-player world along with the Immersive Portal mod (both newest version for MC 1.17.1). I found that as long as an immersive portal is in sight, some weird xray effect appears around the portal as the following screenshot shows:
![2021-08-14_21 57 32](https://user-images.githubusercontent.com/22111513/129448709-b280878b-97f0-464e-9a77-daec612fa65f.png)

After removing clientcommands it just displays normally, so I guess something might be wrong with the mod's rendering module. Any idea how this happens?

**Comment by Hexcede** [comment]
I think this https://github.com/Earthcomputer/clientcommands/issues/269#issuecomment-853542903 is related

**Comment by ImUrX** [comment]
happens to me too, i was using indium, sodium, cc and immersive, and when i remove cc it stops happening :p

**Comment by ImUrX** [comment]
@Earthcomputer this didn't get closed.

Btw I tested it and it works now
