### ISSUE TITLE
[Feature Request] A command for spawning ghost items

### ISSUE THREAD

**Issue by Hexcede** [Earthcomputer/clientcommands#314]
Some sort of command similar to `cgive` or `cghostblock` but creating a ghost item locally, e.g. `cghostitem`.
There are some interesting quirks with ghost items and this would make it easy to test.

Could also support editing the nbt of items locally (e.g. tweaking the held item's nbt), but, that might work better under another command. Would allow for some pretty cool client-side behaviour in conjunction with scripting.

**Comment by xpple** [comment]
What quirks exactly?

**Comment by Hexcede** [comment]
> What quirks exactly?

Mainly just that some items have unique client-sided stuff in their use actions, though, I can't think of any examples atm. The most obvious example being that you can briefly place down ghost blocks, which, might fit a few use cases for #255. I haven't played around with many items, but, unless something special happens in their use event not much interesting should actually happen.

In the past I've also encountered weird behaviour on bukkit servers when glitching ghost items out of things like item GUI menus but I expect that comes down to something specific about inventory states or the plugins rather than the ghost item itself.

One reason for wanting to create ghost/client items in scripting could be implementing something similar to item GUI menus on servers, but, client-sided, or creating item-based tools like recreating something similar to the world edit wand. Though the scripting API might not support all the stuff necessary to do any of that.

**Comment by xpple** [comment]
Yeah, right. Although this sounds cool, I don’t think it has a lot of use-cases. Regarding the client-sided item GUIs, in that case the items wouldn’t be in the player’s inventory, but rather in some other container (which means it’s not needed to give the items as ghost items to the player). 
Also - I don’t exactly where I recall this from - but I think a suggestion similar to this one was actually declined for being too hard to work with (telling apart ghost items and real items).

**Comment by xpple** [comment]
Found it; [this message](https://github.com/Earthcomputer/clientcommands/issues/96#issuecomment-576186308).

**Comment by Hexcede** [comment]
Yeah, those are all good points, and I suppose I missed the discussion there. I'm closing this since it sounds like its either too difficult or would become possible through the scripting feature mentioned there.

Could locally modifying NBT fall under the same scope as well? I'd expect its easier, since creating a whole new item and modifying an existing one are so much different. If so I might open an alternative issue regarding that.

**Comment by xpple** [comment]
Before you do, do you mean modifying the NBT client-sidedly, or server-sidedly as well?

**Comment by Hexcede** [comment]
Just client sided, though, server-friendly would probably be easier to implement.
