### ISSUE TITLE
Fishing RNG Manipulation not working

### ISSUE THREAD

**Issue by thegameisfunny** [Earthcomputer/clientcommands#319]
I'm testing the Fishing RNG Manipulation on a world singleplayer but it keeps casting the rod for a very very long time (20+ min) without actually fishing something or displaying error messages.

**Comment by mariusdkm** [comment]
Did you follow the tutorial in the wiki?
https://github.com/Earthcomputer/clientcommands/wiki/cfish 

Or the tutorial by Earth?
https://www.youtube.com/watch?v=-kJoNBWDBn0

**Comment by thegameisfunny** [comment]
I tried both setups, pretty similar between them, but got no different result.

**Comment by thegameisfunny** [comment]
tried removing other mods and now works

**Comment by xpple** [comment]
What mods were you using?
