### ISSUE TITLE
Changing to CottonMC client commands library? (Enhancement)

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#32]
I was thinking about suggesting this earlier on? I was wondering if it’s possible to implentment, as it could really make a good client commands that can be customised easier.

**Comment by Vonr** [comment]
As far as I can tell, Earthcomputer wants to keep this mod as dependency-free as he can. Introducing Cotton gives the mod another dependency unless I misread something.

**Comment by Earthcomputer** [comment]
I'm not sure how switching to Cotton's client commands would make clientcommands more customizable. Am I missing something?

**Comment by ghost** [comment]
I assumed it would be easier to customise as more people are more common with CottonMC's Libraries and I was more talking about (even though not really specified) the library is updated more as a team of coders are working on it, and it would be easier in the sense of updating for future versions ^0^
