### ISSUE TITLE
/ccrackrng results in being Kicked from the server for "Sending too many packets"

### ISSUE THREAD

**Issue by thegameisfunny** [Earthcomputer/clientcommands#321]
I'm trying to crack the player seed using /ccrackrng, it starts dropping the items to the ground, then it idles for 30 seconds/1 min and then i get kicked for sending too many packets

**Comment by L0um15** [comment]
If you're playing on spigot/paper server. Make sure that there is no anticheat enabled, /ccrackrng is being detected as macro usage.  I had many situations that i confirmed this was the cause.

**Comment by L0um15** [comment]
Also try to avoid any plugins that controls player actions (dropping items, macros, movement etc.) because that may change your RNG.

**Comment by thegameisfunny** [comment]
I guess the server has modified rng and the /ccracking command tries to Crack rng too many times. So I guess I can close the thread.
