### ISSUE TITLE
Remove `/ccheatcrackrng` as it no longer works in Minecraft 1.17 and up

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#322]
As of Client Commands 2.4.8 for Minecraft 1.17.1, running `/ccheatcrackrng` just prints the following message to chat:
> This command no longer works on Java 14+!

Minecraft 1.17.x requires Java 16, but `/ccheatcrackrng` requires Java 13 or older. These conditions conflict with each other; therefore, `/ccheatcrackrng` no longer works in Minecraft 1.17.x and later and should be removed.

**Comment by Earthcomputer** [comment]
This command probably needs to be removed then.

**Comment by hjxtc** [comment]
Yes, but if you don't crack the player's RNG, how to use RNG enchantment.

**Comment by James103** [comment]
Removed in mod version 2.6.5 for Minecraft 1.18.2. Closing as resolved.
