### ISSUE TITLE
/cenchant Doesnt seem to work properly on fabric 1.17+ servers

### ISSUE THREAD

**Issue by skandabhairava** [Earthcomputer/clientcommands#327]
`/cenchant` works 30 - 40% of the times on 1.17+ fabric servers, unlike in versions 1.16.5 where i would get the correct enchants every single time. I tried to enchant my sword with sharpness 4, looting, unbreaking.. but only got sharp 3 on my sword, and it happened twice on 2 swords I tried to enchant. The same goes on with armor items where only one of the requested enchants are actually applied on the item

**Comment by niruvibes** [comment]
Its been working perfectly fine for me, plus it says its may not work cause its a modded server. There is nothing you can do about that.

**Comment by L0um15** [comment]
Do you know which mods these servers are using?

**Comment by skandabhairava** [comment]
The server doesn't contain any huge mods. It just contains lithium, starlight, hydrogen, fabric api

It's probably one of these mods which is not compatible right??

**Comment by L0um15** [comment]
Try without lithium, see what happens.

**Comment by skandabhairava** [comment]
Hmm, yeah that solved the issue; Thanks a lot!! Can someone pls explain why this happens?? I will close the issue/thread immediately. I'm just curious

**Comment by L0um15** [comment]
> Lithium tries to improve a number of systems (game physics, mob AI, block ticking, etc) without changing any behavior.

Personally i have never used lithium serverside. Probably it has something to do with changed ticking system.

**Comment by skandabhairava** [comment]
Kk thanks a lot for helping me

**Comment by DragonEggBedrockBreaking** [comment]
The fix is to disable one of the mixins in config. I have a fork that fixes this on 1.17. From my testing, it is not an issue on 1.18, which is why I will not create a pr for the fix.
