### ISSUE TITLE
`/cenchant`: Allow specifying enchantment level ranges

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#328]
Currently, `/cenchant` supports searching only one enchantment level at a time. However, there are some scenarios where you may end up with redundant enchantments, and it would not be optimal XP- and time-wise to enchant both armor pieces with Protection 4 if you know you are going to get at most Protection 4 anyway from combining the two pieces.

To rectify this, you could allow specifying level ranges for enchantment predicates, such as in the following command:
```mcfunction
cenchant diamond_boots with protection 3..4 with unbreaking 3 with depth_strider 3
cenchant diamond_boots with protection 3..4 with feather_falling 4
```
Where the `3..4` would need to be typed as just `4` in the current Client Commands version (2.5.5, MC 1.17.1).

**Comment by Vonr** [comment]
my opinion is that to should be represented by .. for consistency sake
