### ISSUE TITLE
`/ccrackrng` got stuck and then stop without completing task.

### ISSUE THREAD

**Issue by music-cat-bread** [Earthcomputer/clientcommands#332]
So, I tried using `/ccrackrng` on sigleplayer and it works perfectly, but then I tryied it on minecraft server (1.16.5 papermc hosted on aternos.org) it takes so long and after droping around 5 stacks of cobblestone, it just stop droping them, and it didn't even say that it ended. Then I try using `/cenchant` it says that RNG has to be cracked. Idk why it is happening. Can it be cause because it is on paperMC? But then why do it stops?

Minecraft version: 1.16.5 (fabric) I am only using client commands.
Server Version: Paper MC 1.16.5, hosting: aternos.org.

**Comment by JoakimThorsen** [comment]
Paper breaks rng manipulation: #115

**Comment by music-cat-bread** [comment]
So, is there a way to change it configuration or something like that, to have a normal RNG?

**Comment by JoakimThorsen** [comment]
Not that I know of, no. Iirc it's that way by design
