### ISSUE TITLE
Mod is not recognized as such

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#335]
I downloaded the mod from here into the mods folder but forge doesn't accept it as a mod. To be sure its not from forge/my drive, i also put JEI(Just Enough Items) in the same folder; JEI works, cc doesn't. 
Edit: It is forge beta tho, will try the last stable version now.
![image](https://user-images.githubusercontent.com/94934060/143130026-c3e84cbd-a0fe-4da6-901c-bd134ef63ff3.png)
![image](https://user-images.githubusercontent.com/94934060/143130063-963cb03e-f04f-4e55-bc23-a83ed8d2a934.png)

**Comment by wagyourtail** [comment]
yeah, thats because its a fabric mod https://fabricmc.net/

**Comment by xpple** [comment]
Indeed, see [the installation instruction](https://github.com/earthcomputer/clientcommands#installation).

**Comment by ghost** [comment]
ohh that explains it
