### ISSUE TITLE
/cenchant not working on books

### ISSUE THREAD

**Issue by Dylan-Dough** [Earthcomputer/clientcommands#336]
Not sure if this is a common issue, but when i do a /cenchant for a book it will give me the requirements, but when i open the enchantment table with the requirements it is a completely different enchantment, this also works with /cenchant minecraft:enchanted_book and on

(I use mods im happy to tell u all mods if necessary)

**Comment by DragonEggBedrockBreaking** [comment]
This also happens for me. It used to work fine btw…

**Comment by James103** [comment]
1. Can you please post the full mod list? One way to do that is by attaching a manually generated crash report (done by holding F3+C for 10 seconds) or profiler zip file (from pressing F3+L twice).
2. What server software are you running? The RNG manipulation features of this mod do not work on servers running Bukkit, Spigot, or Paper, nor will they work reliably on Fabric servers with Lithium installed.
3. Have you tested this in singleplayer with only Fabric, Fabric API, and this mod installed? Does it work there?
4. Have you made sure to run `/ccrackrng` right before running the `/cenchant` command?

**Comment by Dylan-Dough** [comment]
> 

thank you for your help and sorry for the late response, i have ran ccrackrng before, and the software is fabric, however lithium is installed server side, if there is a fix for this with lithium with out having to remove it, thank you, and if not i still thank you for informing me

**Comment by James103** [comment]
This may be caused by Lithium's changes to the server. See #327

**Comment by Dylan-Dough** [comment]
James provided with the reason this happens, this is all that was needed
