### ISSUE TITLE
[bug] /cenchant doesn't work for swords in spigot 1.18

### ISSUE THREAD

**Issue by qy9git** [Earthcomputer/clientcommands#342]
The mod works correctly for everything except the sword item (any material). /ccracknrg works fine. The steps: When I wrote a valid command and executed it. It dropped the items and asked me to enchant a dummy then it told me to do 3rd on 14 bookshelves. I broke 1 bookshelf and collected the books dropped and afterward I enchanted the sword for 3 lapis in the 3rd sloth. The process looks perfectly fine but I got completely different enchantments. I tried multiple swords of different materials and never got it working. It works for everything else though (armor, axe, bow...). I also tried different commands but it still kept refusing to work.

**Comment by qy9git** [comment]
![2021-12-19_21 16 52](https://user-images.githubusercontent.com/51716593/146686225-57a58a74-c4fa-4196-b16c-00726fb906a1.png)
I tried the manual version too. Both /ccracking and the manual didn't work, I also had the same issue with the external program. Also, it works with everything except swords, I tried a pickaxe, and works perfectly fine.

If video is needed I can provide that too

**Comment by qy9git** [comment]
I deleted and reinstalled client command 2.6 and the newest farbric api for 1.18/18.1 and the problem is still there.

**Comment by Earthcomputer** [comment]
It's probably a server plugin causing the issue
