### ISSUE TITLE
Find any color block with /cfindblock

### ISSUE THREAD

**Issue by m-sarabi** [Earthcomputer/clientcommands#343]
### Related problems to this suggestion:
Finding a bed, banner. shulker box or any other block that has 16 different color is very hard, because you need to search for every single color of them
### Proposed solution:
- Add a generic block name that then automatically searches for any color of that block, like `/cfindblock any_bed`. this could be expanded to other blocks like `/cfindblock any_copper_block` to find any copper block oxidized or not.
- Add 'any' argument to the /cfindblock command, like `/cfindblock white_bed any`

**Comment by haykam821** [comment]
You can use block tags such as `#minecraft:beds`. Client-side tag modification may be possible in a later version, but that is a separate issue.

**Comment by m-sarabi** [comment]
> You can use block tags such as `#minecraft:beds`. Client-side tag modification may be possible in a later version, but that is a separate issue.

That is actually perfect solution, I didn't know you could do that, Thanks
