### ISSUE TITLE
[BUG] Format error

### ISSUE THREAD

**Issue by zyxkad** [Earthcomputer/clientcommands#346]
When I using `cfind`, `cglow` or `cfindblock` e.t.  
The console response me like `xxxxxx %d xxxxxx`  
I don't think that's your want to see.

**Language: ZH-CN**
**Version: minecraft 1.18.1 + clientcommends 2.6**

**Comment by Earthcomputer** [comment]
Are you sure?
The Chinese translation should look something like "成功使 47 个实体发光"

**Comment by zyxkad** [comment]
> Are you sure?
> The Chinese translation should look something like "成功使 47 个实体发光"

In fact, the text is like "成功使 %d 个实体发光"
I don't know why
Maybe it cause by another mod?

**Comment by Earthcomputer** [comment]
Assuming this must be a mod conflict, haven't seen anyone else say this is happening
