### ISSUE TITLE
cfind misses certain entities when searching NBT

### ISSUE THREAD

**Issue by CodeF53** [Earthcomputer/clientcommands#348]
Recreate:
summon a horse with armor NBT
`/summon horse ~ ~ ~ {Tame:1b,ArmorItem:{id:"minecraft:leather_horse_armor",Count:1b}}`

confirm that our @e search applies to the entity we just created by using it in a vanilla command
`/tp @e[type=minecraft:horse,nbt={Tame:1b,ArmorItem:{id:"minecraft:leather_horse_armor",Count:1b}}] @p`

try /cfind with the same @e search
`/cfind @e[type=minecraft:horse,nbt={Tame:1b,ArmorItem:{id:"minecraft:leather_horse_armor",Count:1b}}]`

![image](https://user-images.githubusercontent.com/37855219/147371908-b191e2ad-bd38-48f5-a2aa-eb35fdc1bd3e.png)

This only applies to certain nbt tags, for example, just searching with the following works just fine
`/cfind @e[type=minecraft:horse,nbt={Tame:1b}]`

**Comment by Earthcomputer** [comment]
One of the caveats of cfind is that it can only work with client-side data.

**Comment by CodeF53** [comment]
horse armor is clientside.

**Comment by Earthcomputer** [comment]
Tame:1b isn't

**Comment by CodeF53** [comment]
Then why does `/cfind @e[type=minecraft:horse,nbt={Tame:1b}]` Work just fine?
