### ISSUE TITLE
/cenchant not working on 1.14.3

### ISSUE THREAD

**Issue by Annabxlla** [Earthcomputer/clientcommands#35]
is there a way for you to release the 1.12.2 version that is compatible with 1.14.3?

**Comment by Platypus3112** [comment]
There is a 1.14.3 version though?

**Comment by Earthcomputer** [comment]
No, there isn't. The /cenchant command has been ported to 1.14.3 but it hasn't been released yet because the "bad action detection" hasn't been fully ported yet. It will be in the next release.
