### ISSUE TITLE
/cfish bobber not getting stuck under water

### ISSUE THREAD

**Issue by burgersarefat** [Earthcomputer/clientcommands#352]
Whenever I run /cfish, I keep throwing it out, but the bobber never gets stuck under the lily pad/block. it just keeps throwing and retracting. 
![image](https://user-images.githubusercontent.com/74564867/149070154-696ea4fe-603d-401b-9a7e-5577076f779a.png)

**Comment by burgersarefat** [comment]
when I was fishing, the blocks weren't there

**Comment by L0um15** [comment]
This often occurs when your goal is to catch unobtainable item from fishing.
Modded servers like (fabric, spigot, paper) can cause this problem too.

I never had any problem with fishing manipulation by using this method on vanilla servers.

I hope this helps. 

1. Make sure you're in correct biome and your goal is to catch one of these items: https://minecraft.fandom.com/wiki/Fishing
2. Prepare fishing rod without any enchantments
3. Find bigger pond (Confirm that area is suitable for fishing)
4. Swim to the middle of the pond (Best results)
5. Place lilypad / carpet 3 blocks away from you
6. Make sure to have fishingManipulation set to manual
7. Aim between you and lilypad
8. Start fishing
