### ISSUE TITLE
Crash/incompatibility with mine little pony

### ISSUE THREAD

**Issue by energy11a** [Earthcomputer/clientcommands#354]
https://github.com/MineLittlePony/Kirin/issues/4

**Comment by wagyourtail** [comment]
hmm, seems to be related to their class labeled
> Utility for rendering objects such as ItemStacks, Entities, and BlockEntities, when there is no client world running.

so this looks valid to me

**Comment by sudofox** [comment]
Just ran into the same issue, delighted to see that someone else has already reported it
