### ISSUE TITLE
/ccrackrng not working on multiplayer worlds

### ISSUE THREAD

**Issue by ChaosPLusen** [Earthcomputer/clientcommands#359]
The /ccrackrng activates and keeps on going for infinitely long. Works just fine in singleplayer

**Comment by erxson** [comment]
It doesnt work on paper

**Comment by Delfite** [comment]
Servers that use plugins are less likely to use the Vanilla Enchantment RNG. It sucks, but it's probably like that for a reason (unfortunately) :/
