### ISSUE TITLE
i cant use enchantingPrediction

### ISSUE THREAD

**Issue by Kabanos69** [Earthcomputer/clientcommands#36]
i tried in alot of ways but every time i do /ctemprule set enchantingPrediction its not working its acting like enchantingPrediction does'nt exist in the mod can some one help me make it work please.

**Comment by ZafotheNinja** [comment]
What version are you in and are you on single or multiplayer?

**Comment by leumasme** [comment]
Wrong Syntax. The correct syntax is
/ctemprule set enchantingPrediction true
Note the "true" at the end.
Close issue?

**Comment by Earthcomputer** [comment]
Let's give him more time to respond first, to see if that is actually the issue. It may have also been related to the issue you DMed me on Discord, which is now fixed in the latest release.

**Comment by Kabanos69** [comment]
The problem was the version ty very much for the help ZafotheNinja
