### ISSUE TITLE
/cfish not working

### ISSUE THREAD

**Issue by zikzaksuper** [Earthcomputer/clientcommands#360]
it is not working, i have lilypad and all but it always says im late by a few ticks... i dont understand, i tried afk mode for 10 min

always says -100ms and "[ ]" ticks behind and it never catches my book

**Comment by goolured** [comment]
i have the same problem
actually it is _sometimes_ useful in single world,but it doesnt work in my server at all

**Comment by mxd185** [comment]
i've been having this issue too, i just figured it out. make sure you have particles set to ALL.

**Comment by Delfite** [comment]
> i have the same problem actually it is _sometimes_ useful in single world,but it doesnt work in my server at all

/cfish and /ccrackrng do not work on Servers that use the "Paper" server plugin manager. It, however, should work fine on most other servers if not all of them.
