### ISSUE TITLE
Allow /cfinditem with fuzzy NBT matching

### ISSUE THREAD

**Issue by Player505** [Earthcomputer/clientcommands#363]
Hello,

A use case for this would be allowing the command to find enchanted items with specific enchants. Ideally this would also be able to do a not exact search. 

For example you have a book with Knock Back and Depth Strider and you use the /cfinditem command to find any books with Knock Back it would be able to find that book even though its not an exact nbt match.

**Comment by Earthcomputer** [comment]
cfinditem now uses item stack components as with all other vanilla commands, making this possible now.
