### ISSUE TITLE
[suggestion] tnt knockback based player finder

### ISSUE THREAD

**Issue by krispyking24** [Earthcomputer/clientcommands#364]
idk how to explain it but here's the video i found showcasing it explanation starts around 1:50 look at around 4:10 for a triangulation method 
https://youtu.be/WHDtl_EvDbE

**Comment by xpple** [comment]
Very interesting! @haykam821 and I have been working on this. The progress we have so far is on my fork on the branch [tnt-player-finder](https://github.com/xpple/clientcommands/tree/tnt-player-finder).

**Comment by sylv256** [comment]
Very interesting!
