### ISSUE TITLE
crackrng

### ISSUE THREAD

**Issue by githubforzack** [Earthcomputer/clientcommands#368]
/ccrackrng isnt working for me, like it drops the items but it doesn't give me a player seed

**Comment by 0ItsHydra** [comment]
Yeah I've been having the same problem for morme than a week

**Comment by erxson** [comment]
Maybe, you used this on Paper server?

**Comment by L0um15** [comment]
It seems that you're playing on a paper server. They are using several optimalizations that interfere with crackrng. See if issue persists on vanilla server.
