### ISSUE TITLE
crashing when going into realms

### ISSUE THREAD

**Issue by superboom7** [Earthcomputer/clientcommands#372]
title explains it

**Comment by Earthcomputer** [comment]
Give a crash log

**Comment by superboom7** [comment]
[crash-2022-03-02_20.47.47-client.txt](https://github.com/Earthcomputer/clientcommands/files/8238281/crash-2022-03-02_20.47.47-client.txt)

**Comment by superboom7** [comment]
[crash-2022-03-12_19.04.16-client.txt](https://github.com/Earthcomputer/clientcommands/files/8238284/crash-2022-03-12_19.04.16-client.txt)

**Comment by superboom7** [comment]
when i joined my singleplayer then realm it worked fine

**Comment by Earthcomputer** [comment]
The first one is an unrelated Forge crash log

**Comment by superboom7** [comment]
yea i didnt mean to send that

**Comment by superboom7** [comment]
yep just tested it joined realm first crashed joined singleplayer then realm its fine

**Comment by Earthcomputer** [comment]
Does the same thing happen if you try to join a multiplayer server instead of a realm? That would make it easier for me to test

**Comment by superboom7** [comment]
i will check

**Comment by superboom7** [comment]
i crash joining multiplayer first

**Comment by superboom7** [comment]
i join singleplayer first then realms and im fine

**Comment by superboom7** [comment]
this is 1.18.2 fabric btw
