### ISSUE TITLE
[suggestion] being able to force ordered enchantment list

### ISSUE THREAD

**Issue by zhguyu** [Earthcomputer/clientcommands#374]
This is a minor feature request:

Because of my personal OCD I'd always like to have the enchantments in my equipment to be in a specific order. I usually do that by manually editing the NBT using NBTExplorer. It would be really nice if there's an option which allows us to indicate that we'd like the enchantments in the desired item (whether from the enchanting table or fishing) to be in the exact order that we instructed in the command, if possible. If the desired combination is common, then it shouldn't make the RNG manipulation effort (number of items to throw/fishing rod recast times before success) significantly more tedious. If the combination is rare... well, it's rare anyway.

**Comment by erxson** [comment]
Cool idea

**Comment by unilock** [comment]
In the meantime, there's [Better Enchanted Books](https://modrinth.com/mod/better-enchanted-books), which orders enchantments in tooltips entirely client-side.

Although, IIRC, it doesn't work on >=1.19.3. But it shouldn't be too difficult to port, were one to try a hand at it.
