### ISSUE TITLE
{suggestion} add a map loader 

### ISSUE THREAD

**Issue by tympanicblock61** [Earthcomputer/clientcommands#376]
can you add a map loader that loads map.dat files so we can use maps on servers without remaking them?

also can i be unbanned from the discord i only sent a link and this was a month ago

**Comment by xpple** [comment]
Could you elaborate on your idea?

**Comment by tympanicblock61** [comment]
> Could you elaborate on your idea?

yes i could, what i know of is that the map.dat files in a world save store the image of each map so i was wondering if you could have them in a folder in the .minecraft directory and do a command like /cmapload map_3.dat and it loads it to the map you have in your hand, not in survival obviously

**Comment by xpple** [comment]
This is already possible; use the `cgive` command with the desired map id as NBT.

**Comment by tympanicblock61** [comment]
> This is already possible; use the `cgive` command with the desired map id as NBT.

no i mean like on servers so that you won't have to keep making map art again and again on creative servers

**Comment by Gaming32** [comment]
That's exactly what the command does. It gives you any item in creative mode. It's like the `/give` command, but you don't need op (you do need creative mode though).

**Comment by tympanicblock61** [comment]
> That's exactly what the command does. It gives you any item in creative mode. It's like the `/give` command, but you don't need op (you do need creative mode though).

no you don't understand what i am asking, i am asking if you can make a addon for loading map.dat files onto a map on a server not a world because /cgive minecraft:map{map:1} doesn't work unless the server has that map in the files

**Comment by Gaming32** [comment]
Ah, I don't think you can send map data to the server.

**Comment by tympanicblock61** [comment]
> Ah, I don't think you can send map data to the server.

ok that's what i was wondering, can i get a unban from. the discord it's fine if i cant
