### ISSUE TITLE
1.14.2 seems broken.

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#38]
The 1.14.2 version for fabric seems broken, at least to me. It doesn't work, and if viewed via the ModMenu mod it shows up in a gray-ish colour, meaning there's something wrong with it.
I tried it with no mods except the API, on a fresh install of minecraft and with MultiMC.

**Comment by Earthcomputer** [comment]
Is this still an issue in 1.14.4? Can you define "it doesn't work"?
