### ISSUE TITLE
[suggestion] add an option to cfish goals that only gives a single enchantment

### ISSUE THREAD

**Issue by talhoid** [Earthcomputer/clientcommands#381]
i want to enter a command like this:
`/cfish add-enchanted-goal minecraft:enchanted_book with only mending 1`
and not
`/cfish add-enchanted-goal minecraft:enchanted_book with mending 1 without aqua_affinity * without bane_of_arthropods * without blast_protection * without channeling * without binding_curse * without vanishing_curse * without depth_strider * without efficiency * without feather_falling * without fire_aspect * without fire_protection * without flame * without fortune * without frost_walker * without impaling * without infinity * without knockback * without looting * without loyalty * without luck_of_the_sea * without lure * without multishot * without piercing * without power * without projectile_protection * without protection * without punch * without quick_charge * without respiration * without riptide * without sharpness * without silk_touch * without smite * without soul_speed * without sweeping * without thorns * without unbreaking *`.
(generated from script)

**Comment by Earthcomputer** [comment]
This is covered by #373

**Comment by xpple** [comment]
Implemented by [this commit](https://github.com/Earthcomputer/clientcommands/commit/5bb55ebc347461c306d14f7f4e8bcdec76759e8b).
