### ISSUE TITLE
1.14.3 cant load the java

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#39]
I put the Latest Java into my mods folder and started up minecraft and selected Forge version after that i pressed play and launched minecraft but when it loaded it said (the name of the Java) could not be loaded because of an error and i only putted the Java into my mods folder

**Comment by MCRcortex** [comment]
no logs
plz add logs

**Comment by Earthcomputer** [comment]
Also the 1.14.3 version is Fabric not Forge
