### ISSUE TITLE
Fishing RNG Manipulation rates

### ISSUE THREAD

**Issue by PanCake0428** [Earthcomputer/clientcommands#393]
It seems like the afk option for /ctemprule set fishingManipulation afk only has a 20-50% success rate and not 76%? I tried it on 2 servers under 50 ping and both had extremely low succession rates and it always said "didn't get the correct loot with the correction of -[]ms, could have been [] ticks ahead.

**Comment by PanCake0428** [comment]
Update: I tested the command on 36ms ping and I only got a 25% (10/40 items) for the enchantment goals I set.

**Comment by Earthcomputer** [comment]
Oof. But what do you want me to do about it?

**Comment by PanCake0428** [comment]
Is there anything I could do to improve the rates?

**Comment by Earthcomputer** [comment]
Nope, low rates mean your connection is less reliable, which there's no workaround for, at least from the point of view of a Minecraft mod. Anything relating to making your connection more reliable (not faster necessarily, just more consistently the same speed, but the two go hand in hand) would help. If you can't do that, then you're simply stuck with these rates I'm afraid. Either way, nothing I can do about it.
