### ISSUE TITLE
/cfish add-goal does not give autocomplete options for goals

### ISSUE THREAD

**Issue by MonetaryGains** [Earthcomputer/clientcommands#401]
To specify a non-enchanted goal in cfish, you have to type out the goal manually and its just for the regular add-goal. The add-enchanted-goal works fine with autocomplete but it just seems to be bugged with add-goal. 

e.g /cfish add-enchanted-goal [gives autocompletion options]
      /cfish add-goal [no autocompletion options] but works when typed in manually

**Comment by thecolonel63** [comment]
I can confirm, it is rather annoying. I think this is an accidental side-effect of changing the cfish command to add the "exactly" option.

**Comment by Earthcomputer** [comment]
Seems to have been fixed
