### ISSUE TITLE
Add `/ceffect` that adds effects client side

### ISSUE THREAD

**Issue by m-sarabi** [Earthcomputer/clientcommands#427]
Now that in Minecraft 1.19 you can not increase gamma to be able to see in dark and `/cgamma` being broken, I think it is a good time to add a `/ceffect add <effect> <time> <multiplier>` to add effects to the client. It can only be nightvision effect, but other effects could also be useful.
for example:

- `/ceffect removeall` to remove every effect.
- `/ceffect add slowness` to move slower, useful for while building
- `/ceffect add mining_fatigue` to avoid insta mining
- optional `--no_particles`

**Comment by haykam821** [comment]
If this command is added, I think it should use the same syntax as the vanilla equivalent, with the exception of the targets argument. Also, as a side note, #428 fixes the issue with `/cgamma`.

**Comment by m-sarabi** [comment]
Closing it as `/cgamma` is fixed
