### ISSUE TITLE
Execution of the /cfind instruction crashed

### ISSUE THREAD

**Issue by yuyi2439** [Earthcomputer/clientcommands#431]
[crash-2022-07-07_11.05.43-client.txt](https://github.com/Earthcomputer/clientcommands/files/9060067/crash-2022-07-07_11.05.43-client.txt)

**Comment by CodeF53** [comment]
I have this issue aswell
https://crashy.net/7ssyRxOrCUDuQPVvD6jc

**Comment by Earthcomputer** [comment]
Can you both try and find out which mod it's conflicting with. This doesn't happen with just clientcommands (and fabric api)

**Comment by CodeF53** [comment]
Will look into it tomorrow

**Comment by yuyi2439** [comment]
Clientcommands mod conflicts with oh-my-minecraft-client mod
[oh-my-minecraft-client](https://github.com/plusls/oh-my-minecraft-client)
xaero-map-addition mod depends on it
I need a feature of xaero-map-addition mod

**Comment by Earthcomputer** [comment]
Duplicate of #423
