### ISSUE TITLE
any way to fix RNG on a paper server I own?

### ISSUE THREAD

**Issue by NutNutty64** [Earthcomputer/clientcommands#433]
Title says it all, is there a plugin or setting / could a plugin be made that makes the RNG manipulatable again?

**Comment by OneYellowLemon** [comment]
No. This is the patch that breaks it, so you could compile Paper yourself and remove it.

https://github.com/PaperMC/Paper/blob/master/patches/server/0070-Use-a-Shared-Random-for-Entities.patch

**Comment by eris-webserv** [comment]
Maybe make a custom Paper fork with this removed, among other things? TechniPaper's a good name.

**Comment by ehylo** [comment]
Already exists [here](https://github.com/ImUrX/RNGPaper/actions/workflows/build.yml)

**Comment by eris-webserv** [comment]
If somoene could do that for [purpur](https://github.com/PurpurMC/Purpur) that would be amazing.

**Comment by ImUrX** [comment]
[its configurable](https://github.com/PurpurMC/Purpur/blob/ver/1.19/patches/server/0285-Add-toggle-for-RNG-manipulation.patch) in purpur

**Comment by eris-webserv** [comment]
Ah.
