### ISSUE TITLE
Picking up XP breaks XP seed for /cenchant, making it non-accurate

### ISSUE THREAD

**Issue by eris-webserv** [Earthcomputer/clientcommands#435]
Title.
Fucks me up a lot when using it. A patch would be nice.

**Comment by Coderx-Gamer** [comment]
It is not a problem with the mod and impossible to fix this without server-side modifications so it cannot be "patched" unfortunately.

**Comment by eris-webserv** [comment]
Technically not? Just remove the seed when you collect XP.
