### ISSUE TITLE
[Suggestion] Ability to reset XP seed for /cenchant to get enchants the mod thinks are impossible with current seed

### ISSUE THREAD

**Issue by eris-webserv** [Earthcomputer/clientcommands#436]

**Comment by TheoCGaming** [comment]
Would this be possible on servers? Is there an existing way to reset the enchantment seed, such as breaking a bookshelf or relocating the table? Is the mod already able to discard the current seed in favor of a new one?

**Comment by eris-webserv** [comment]
Resetting the seed is completely possible.
Sometimes enchanting will make the seed random, and then it could be possible (within a timespan) to get the enchants you want.

**Comment by Earthcomputer** [comment]
You have to do that yourself by doing one of the forbidden actions, most effective is relogging. The mod will automatically detect this.
