### ISSUE TITLE
/cgamma setting the gamma to 0.5

### ISSUE THREAD

**Issue by xyqef** [Earthcomputer/clientcommands#437]
doing /cgamma only changes my gamma to 0.5 no matter what number i put

**Comment by haykam821** [comment]
What values are you using? Until version 2.7.1 is released, only values between 0 and 1 will work without the gamma resetting to the default value of 0.5.

**Comment by James103** [comment]
As a workaround, there are versions of Malilib and Tweakeroo available for 1.19 through community-maintained ports: https://kosma.pl/masamods/

Download `malilib-fabric-1.19-0.12.1.jar` and `tweakeroo-fabric-1.19-0.13.3.jar`, place those files in the mods folder of your Minecraft instance, then restart the game. Go into the config screen for Tweakeroo by doing X+C or via Mod Menu, click `Tweaks`, and enable `tweakGammaOverride`. Set your desired gamma value in Generic > `gammaOverrideValue`.
