### ISSUE TITLE
Inline commands from client command chat output are executed server-side only, rather than client-side first

### ISSUE THREAD

**Issue by James103** [Earthcomputer/clientcommands#438]
When a client command is executed and produces output that contains inline commands, such as the coordinates in `/cfind @e`, the inline commands are executed server-side only rather than client-side first.

This means client commands do not work when executed from clicking on a chat message; they only work when executed directly.

To reproduce:
1. Create a new instance with Fabric Loader 0.14.7 and Minecraft 1.19.
2. Install Fabric API 0.57.0.
3. Install Client Commands 2.7.
4. Start the instance.
5. Create a new world with cheats enabled.
6. Run `/cfind @e`
7. Click on one of the sets of coordinates in the output of the above command.
8. `clook block <x> <y> <z>` fails to execute on the server side due to "Unknown or incomplete command"
9. Open chat, type `/clook block 123 456 789`, then press enter.
10. The command executes successfully, adjusting your rotation.

This is likely because 1.19 separated commands and chat messages into their own, breaking setups like this in the process.

**Comment by Earthcomputer** [comment]
Hi, this is an issue with Fabric Client Commands API, please report it there.
