### ISSUE TITLE
it doesnt let me open minecraft with the mod with 1.19+

### ISSUE THREAD

**Issue by Dall4-32** [Earthcomputer/clientcommands#440]
when i  try to open the game it just comes back to the launcher telling me there is a resourcepack/modpack error

**Comment by Earthcomputer** [comment]
Can you send the error?

**Comment by Dall4-32** [comment]
it has no message error i use tlauncher it just crashes if i try to open the game

**Comment by Earthcomputer** [comment]
So there is an error but there isn't an error. Nah can't help you

**Comment by Dall4-32** [comment]
ok
