### ISSUE TITLE
/cfish doesn't work on PaperMC Servers

### ISSUE THREAD

**Issue by raining237** [Earthcomputer/clientcommands#446]
I was using the cfish command and I just could not get it to work on my PaperMC server but when I joined a singleplayer, it worked fine. Version is 1.19.2 and to clarify, the when the rod tries to throw itself out, the rod sometimes pauses and stops throwing. Also, when the rod throwing does work, the reeling does not work.

**Comment by CzechHek** [comment]
RNG manipulation doesn't work on Paper. This mod clearly states that when trying to /ccrackrng and such.

**Comment by raining237** [comment]
Sorry dumb question, thanks for the quick response!

**Comment by CzechHek** [comment]
> Sorry dumb question, thanks for the quick response!

Make sure to mark this issue as closed.
