### ISSUE TITLE
Obfuscated Text Glitching

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#45]
Text that is between 2 Obfuscated Text parts is sometimes glitchy.
Example: https://streamable.com/5r2oc
As you can see, the text in the middle of the 2 Obfuscated Characters Glitches between being normal and Obfuscated. This is supposed to be Normal Text, and it is when viewing with a vanilla Client.
I have also seen this ingame, on a Hypixel Archievement Chat Message.
This does not happen consistently, but very commonly.
The Server MOTD in the Video is from play.minevict.us

**Comment by leumasme** [comment]
Only clientcommands and the required fabric api mod installed

**Comment by Earthcomputer** [comment]
Not a clientcommands issue.

**Comment by leumasme** [comment]
What else? Is this Fabrics fault?

**Comment by Earthcomputer** [comment]
I don't know but clientcommands doesn't touch text rendering. You should try with just Fabric installed and with vanilla and see if it still does it.

**Comment by Mhowser** [comment]
I get the same rendering glitch and I'm on Linux, so it must be a 1.14 bug.

**Comment by AJMFactsheets** [comment]
Perhaps it is because of: [MC-134865](https://bugs.mojang.com/browse/MC-134865)
