### ISSUE TITLE
Fishing bobber out of water, mainpulation won't work.

### ISSUE THREAD

**Issue by FeiSaMa** [Earthcomputer/clientcommands#450]
/cfish command didn't work in any waters.
And I trid /cfish again in single player world with only loading this mod.
Minecraft version: 1.19.2
Cilent commands version:2.7.3
![屏幕截图(34)](https://user-images.githubusercontent.com/83686454/190852206-6d44398d-f70a-4363-beb1-bc2c88293b76.png)
![屏幕截图(33)](https://user-images.githubusercontent.com/83686454/190852209-75b8bf48-3193-42ef-8fb7-59d42d781515.png)

**Comment by CzechHek** [comment]
You have to throw the bobber under a block. But since you probably want mending books and such it has to be something like a lilipad. I am pretty sure the game says this information when cfish fails.

**Comment by Coderx-Gamer** [comment]
You need to throw the bobber under a lily pad and it should work, other blocks will not work though because of the afk fishing nerf so you couldn't catch anything good if there are blocks such as wood planks nearby.
