### ISSUE TITLE
Unknown or incomplete commands

### ISSUE THREAD

**Issue by Thrumptus** [Earthcomputer/clientcommands#452]
Commands from this mod are shown as invalid but still function correctly when run
![bug](https://user-images.githubusercontent.com/93964920/193882518-53b4fbb5-38a1-4bed-8f10-a2d9a7c1abce.png)

**Comment by Thrumptus** [comment]
Issue caused by Konkrete/Fancymenu

**Comment by haykam821** [comment]
This issue relates to Keksuccino/Konkrete#15, but it seems to be a problem on their side. Client Commands registers its commands the standard way:

https://github.com/Earthcomputer/clientcommands/blob/fbe5bfc6bf6b6584a205df45217e76cd2544b2de/src/main/java/net/earthcomputer/clientcommands/ClientCommands.java#L23
