### ISSUE TITLE
I enabled rng on Purpur, but fishingManipulation still doesn't work.

### ISSUE THREAD

**Issue by ghhcbef1** [Earthcomputer/clientcommands#454]
Purpur is a fork of paper
https://github.com/PurpurMC/Purpur

**Comment by Earthcomputer** [comment]
Looks like you need to set `settings.entity.shared-random` in the Purpur config, with a sufficiently up-to-date version of Purpur. If that doesn't work, it's not our problem, RNG-related issues are only valid if it doesn't work on vanilla servers.
