### ISSUE TITLE
fishing doesn't work on minehut

### ISSUE THREAD

**Issue by E-underscore-3** [Earthcomputer/clientcommands#463]
for what ever reason, the fishing manipulation doesn't work on minehut servers. with default settings, it would appear that the fishing spam thing that it does to find fishing loot starts then stops after a second or two. when it does cast the bobber out, it seems to only be an error and it doesn't actually work. i'm wondering whether there is a fix to this issue or if it isn't fixable due to the way minehut operates servers. a possible reason it didn't work is that it tells me in chat that the server is modded and the rng manipulation won't be accurate, but i know there are no mods installed on the server. although possible plugins may also be at fault.

**Comment by Adapron** [comment]
i used the fishing manipulator on a minehut spigot server and it worked fine. check if you do everything correctly.

**Comment by E-underscore-3** [comment]
i did, but there server was paper not spigot. i have made my own minehut server and set it to 1.18 vanilla (i used the 1.18 version) and it was fine. i just want to know if there are any fixes

**Comment by TgZ39** [comment]
You have to build your own paper version without this patch: https://github.com/PaperMC/Paper/blob/master/patches/server/0073-Use-a-Shared-Random-for-Entities.patch
But don't ask me how I don't know how.
