### ISSUE TITLE
Doesnt detect player is on server

### ISSUE THREAD

**Issue by RealIndrit** [Earthcomputer/clientcommands#465]
IP: play.wynncraft.com

cping cant ping server and assumes its SinglePlayer. 

![image](https://cdn.discordapp.com/attachments/703598704266969099/1044264667171782797/2022-11-21_15.54.37.png)
![image](https://cdn.discordapp.com/attachments/703598704266969099/1044260310846029925/image.png)

It looks like Wynncraft doesnt let client ping server properly, but clientcommands should return "Failed to ping" instead of "SingelPlayer world"

**Comment by Earthcomputer** [comment]
Duplicate of #392
