### ISSUE TITLE
Fishing manipulation is not working

### ISSUE THREAD

**Issue by m-sarabi** [Earthcomputer/clientcommands#474]
When trying to cast the fishing rod with fishing manipulation on, the rod gets pulled out of the water immediately after throwing it under a lily pad. When casting the bobber out of the water, the error is shown and the fishing rod is never pulled back.

my mods:

- fabric api 0.69.0+1.19.3
- clientcommands 2.7.7

**Comment by 4LaERz0GWNnuZqmnH** [comment]
https://imgur.com/a/2EaSvpS - An example video. Note that I only click once to cast. I cast above the lilypads once to show that it's detecting that I'm fishing.
Windows 11
Fabric 0.14.11
Fabric api 0.69.1+1.19.3
clientcommands 2.7.7

**Comment by WolfEllobo** [comment]
> https://imgur.com/a/2EaSvpS - An example video. Note that I only click once to cast. I cast above the lilypads once to show that it's detecting that I'm fishing. Windows 11 Fabric 0.14.11 Fabric api 0.69.1+1.19.3 clientcommands 2.7.7

https://imgur.com/nH78TLN - Fishing manipulation is not working too.
Fabric 0.14.12
mods
clientcommands-2.7.7
fabric-api-0.70.0+1.19.3

**Comment by Earthcomputer** [comment]
Fixed by https://github.com/Earthcomputer/clientcommands/commit/fb03c4774a24d5f7e6a34a1d49d1c0c5a4ee95bd
