### ISSUE TITLE
help ..

### ISSUE THREAD

**Issue by RegularMinecrafter** [Earthcomputer/clientcommands#49]
Hey EC, im retard.. and idk how to install and use the .cbook random, can someone help me? 
thx

**Comment by Earthcomputer** [comment]
Have you read the README?

**Comment by RegularMinecrafter** [comment]
no...

**Comment by RegularMinecrafter** [comment]
sorry :')

**Comment by RegularMinecrafter** [comment]
Where do I have to place the folder "clientcommands" and the .Jar?

**Comment by Earthcomputer** [comment]
clientcommands is not a folder. The Jar goes in the mods folder, along with the Fabric API.

**Comment by Mhowser** [comment]
It's not `.cbook` it is /cbook

**Comment by RegularMinecrafter** [comment]
Thanks EC!
