### ISSUE TITLE
The max level of enchantment of efficiency is 5, not 4 in 1.19.3

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [Earthcomputer/clientcommands#493]

**Comment by m-sarabi** [comment]
The max level of efficiency you can get from fishing or an enchanting table is 4 if that is what you mean!

The mod only shows the max level of enchant that you can actually get, the same is for sharpness for example.

**Comment by Earthcomputer** [comment]
OP didn't provide enough information, but based on what they're probably talking about, @m-sarabi is correct.
