### ISSUE TITLE
/cenchant does not work while enchanting boot with feather falling

### ISSUE THREAD

**Issue by zhenban** [Earthcomputer/clientcommands#499]
I use this command on a stock server which version is 1.19.3
/cenchant minecraft:diamond_boots with minecraft:feather_falling 4
But feather falling did not show up, the command also does not work in single player mode

**Comment by Earthcomputer** [comment]
Most likely fixed by https://github.com/Earthcomputer/clientcommands/commit/e7b9ec1fe526571d026603fac29894ed138cfab1
