### ISSUE TITLE
Add seed and limit arguments to /cbook

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/clientcommands#5]
- seed argument to workaround some servers not allowing you to sign large books
- limit argument to workaround some servers not allowing 50 page books

**Comment by JABirchall** [comment]
+1 @Earthcomputer add an option to do x pages at a time. A server I tried this on has a plugin to block large packets (ViaVersion or protocallib) But pasting each page and closing the book bypasses this.

**Comment by Vonr** [comment]
Page option is done on my fork, should be committed into main soon. Also BIG thanks to Earth for helping me troubleshoot and explaining some Java shenanigans :P

**Comment by Earthcomputer** [comment]
Partially addressed by #7

**Comment by Earthcomputer** [comment]
Implemented in the latest version
