### ISSUE TITLE
Fabric mod??? What

### ISSUE THREAD

**Issue by florianpunz** [Earthcomputer/clientcommands#50]
So i downloaded the newest version and all the older versions always worked but when i started it said its a fabric mod and when i start with fabric it just crashes. Is this a bug or something

**Comment by Earthcomputer** [comment]
Can you give the crash log?

**Comment by masonrex** [comment]
i have the same problem with mine. how can i get the crash log

**Comment by Earthcomputer** [comment]
The crash log should be in `.minecraft/crash-reports`, or else in `.minecraft/logs`. Not installing the Fabric API (which is different from the Fabric loader which also needs to be installed) can cause a crash on startup.
