### ISSUE TITLE
Oversight in ClientBlockPredicateArgumentType

### ISSUE THREAD

**Issue by xpple** [Earthcomputer/clientcommands#509]
A `BlockArgumentParser.BlockResult` is designed to match multiple block states of the same block. For example `grass_block` would match both `grass_block[snowy=false]` and `grass_block[snowy=true]`. The argument type does not reflect this behaviour however, as in [these lines](https://github.com/Earthcomputer/clientcommands/blob/b9d903449d22692fd92b6a9b88eee7be5930257b/src/main/java/net/earthcomputer/clientcommands/command/arguments/ClientBlockPredicateArgumentType.java#L147-L154) only one state is ever matched. This can simply be fixed by removing the `break` statement, but perhaps there is a better, more optimised solution.

Edit: Why not just remove the `BitSet` design altogether?

**Comment by Earthcomputer** [comment]
I'm not seeing why that code is incorrect. The `break` statement is for the predicate loop, not the outer states loop. The `BitSet` is there to optimize checking millions of blocks with the predicates.

**Comment by xpple** [comment]
Wow, that was stupid of me. I changed the argument type for SeedMapper and removed the loop, not realising I had to remove the `break` statement as well. Then I ran into some issues and assumed they'd appear here as well. Sorry!

**Comment by xpple** [comment]
By the way, why instead of concatenating the predicates using `Predicate#or`, do we keep track of a list of predicates?

**Comment by Earthcomputer** [comment]
We don't really "keep track" of a list, we build a list and then immediately use it

**Comment by xpple** [comment]
I mean something like this.
```java
Predicate<BlockState> predicate = results.stream()
    .map(ClientBlockPredicateArgumentType::getPredicateWithoutNbt)
    .reduce(state -> false, Predicate::or);

// slower than lazy computation but thread safe
BitSet mask = new BitSet();
BlockState state;
for (int id = 0; (state = Block.STATE_IDS.get(id)) != null; id++) {
    if (predicate.test(state)) {
        mask.set(id);
    }
}
```
