### ISSUE TITLE
Curse of Binding armor breaks /ccrackrng and /cenchant

### ISSUE THREAD

**Issue by ZenithRogue** [Earthcomputer/clientcommands#51]
While you are wearing armor with curse of binding, you become unable calculate your seed, as these commands try to drop your armor pieces continuously. This means you have to die first, or let the armour break on its own

**Comment by Earthcomputer** [comment]
Fixed, I'll release the fix when I get internet access again tomorrow.
I also improved the throw order so that it tries to throw stackable items first, in order to avoid throwing your valuable tools and armour :)

**Comment by ZenithRogue** [comment]
Oh sweet, that was quick!
