### ISSUE TITLE
Incorrect error statement

### ISSUE THREAD

**Issue by JakeWolf35** [Earthcomputer/clientcommands#515]
In version 2.7.9, the dependency of fabric api 0.37.1 displays as just "fabric 0.37.1" in the Incompatible mod set window.
This made it a bit harder to find the mistake.
![image](https://user-images.githubusercontent.com/129426868/228924187-e888b4b3-2784-461c-98ab-324303277b2d.png)

**Comment by xpple** [comment]
Good suggestion, clientcommands and clientarguments should probably change the dependency to be on `fabric-api`, instead of `fabric`.
