### ISSUE TITLE
Add delay when dropping items for the /ccrackrng command

### ISSUE THREAD

**Issue by GodGun968** [Earthcomputer/clientcommands#519]
Some servers have strict anti-cheating, moving/dropping items too fast will only drop a few items instead of the correct amount of items . So a custom delay should be added between dropping items though I don't know if this is possible.

**Comment by Earthcomputer** [comment]
Added a new config option in https://github.com/Earthcomputer/clientcommands/commit/e7b9ec1fe526571d026603fac29894ed138cfab1 called `itemThrowsPerTick`. You can set it to a fractional value to spread item throws across multiple ticks. E.g. a value of `0.2` throws one item every 5 ticks.
