### ISSUE TITLE
Assistance in backtracking clientcommands to 1.14.3

### ISSUE THREAD

**Issue by Rolandsteele** [Earthcomputer/clientcommands#52]
Basically, I'm trying to retrofit my client to run client commands on 1.14.3, buttttt I'm a bit lost as to what needs to happen to do that. Whether the 1.14.4 versions might be backwards compatible, or the client commands as well. Any assistance is appreciated.

**Comment by MCRcortex** [comment]
theoreticaly, all you should need to do is change the version and mappings in gradle.properties to 1.14.3 mappings

**Comment by Rolandsteele** [comment]
Right... I appreciate the promptness @MCRcortex . If you have the time/patience, explain it to me like I'm 5? xD

**Comment by Rolandsteele** [comment]
Alllright, so I've got build 13 for 1.14.3 fabric-wise. But past that, I'm basically completely lost.

**Comment by MCRcortex** [comment]
have you run gradlew build
?
because once youve done that you would have built your clientcommands.jar
then just install it like any other fabric project

**Comment by Earthcomputer** [comment]
You will need some coding experience to be able to do this. If not, then I'm afraid I don't have the time to help as it's not the simplest thing in the world. There is a 1.14.3 version of this mod, but unfortunately it's old and doesn't contain the latest features and fixes.
