### ISSUE TITLE
/cenchant error

### ISSUE THREAD

**Issue by Turtl31** [Earthcomputer/clientcommands#520]
When i try to do in my singleplayer
/cenchant minecraft:diamond_leggings with minecraft:protection 4 with minecraft:thorns 2 with minecraft:unbreaking 3
It says "Its impossible or would take too long to get those enchantments"
I did /ccrackrng but still

i even tried to re log in to my game

idk if its a bug or im doing something wrong
minecraft 1.19.3 fabric

**Comment by Earthcomputer** [comment]
I would try for something a little more common, that can happen when you ask for a very rare combination.
