### ISSUE TITLE
CEnchant suggests impossible items for current protocol version

### ISSUE THREAD

**Issue by RaphiMC** [Earthcomputer/clientcommands#521]
The /cenchant command suggest items which are impossible to obtain in the current version.
Example: Join a 1.8 server and type `/cenchant netherrite`. Observe netherrite items being suggested.
Enchantments are already being filtered and items were being filtered in earlier clientcommands versions so it would be a nice feature to have impossible items filtered again

**Comment by Earthcomputer** [comment]
This was likely because multiconnect used to modify the registries
