### ISSUE TITLE
Can't stop crack RNG

### ISSUE THREAD

**Issue by User670** [Earthcomputer/clientcommands#53]
On a seems-to-be-modded server. /ccrackrng with MC 1.14.4 and mod 2.3.3, mod keeps throwing items non-stop and even resumes after relogging; with MC 1.14.4 and mod 2.3.4, mod sometimes automatically restarts throwing items. /ctask doesn't show this as a task and thus cannot be stopped.

**Comment by Earthcomputer** [comment]
Fixed
