### ISSUE TITLE
/cfish doesnt appear to exist

### ISSUE THREAD

**Issue by neonyyz** [Earthcomputer/clientcommands#533]
![Screenshot 2023-06-08 161327](https://github.com/Earthcomputer/clientcommands/assets/79551194/6d9f5087-2a1c-4213-81ea-3c55fc1ef7d9)

Vanilla 1.20 Server, removed mod and reinstalled, still nothing.

**Comment by Gaming32** [comment]
`/cfish` was removed, to my knowledge. Fishing manipulation is no longer possible on 1.20.

**Comment by Earthcomputer** [comment]
Fishing manipulation was fixed in 1.20. It's still there if you're on a 1.19 or below server.
