### ISSUE TITLE
The cfish command has been removed in Minecraft 1.20

### ISSUE THREAD

**Issue by SpraAng** [Earthcomputer/clientcommands#534]
where is my /cfish 
TAT

**Comment by vablings** [comment]
cfish was fixed in 1.20

**Comment by Mudxiej** [comment]
> cfish was fixed in 1.20

Wdym was fixed? Is it no longer possible?

**Comment by Gaming32** [comment]
Correct.

**Comment by Mudxiej** [comment]
Damn, that was my favorite method to gear up in early game. Free enchanted books from thin air

**Comment by haykam821** [comment]
Since loot tables can no longer be manipulated as of Minecraft 1.20, the `cfish` command has been removed. If you are playing on an older version where loot tables can be manipulated through [ViaFabricPlus](https://modrinth.com/mod/viafabricplus), the command will be present.

**Comment by ToxicAven** [comment]
Would there somehow be a way to use the rng weights of the world to make it work again? obviously it wouldn't be very useful since getting those weights would be near impossible, but theoretically?

**Comment by Earthcomputer** [comment]
You would be able to predict what you get from fishing, but wouldn't be able to change that result.

**Comment by Cyclopropinon** [comment]
u could implement `/cfish predict` please?

**Comment by Mudxiej** [comment]
> u could implement `/cfish predict` please?

YES PLEASE

**Comment by Link98745** [comment]
This says fixed in 1.20 but the cfish command is not showing. What is going on? https://www.youtube.com/watch?v=-kJoNBWDBn0&ab_channel=Earthcomputer

**Comment by Link98745** [comment]
We need a way to get mending books without villagers

**Comment by Triv177013** [comment]
What would be a theoretical work around for this. Assume you already have the world seed. My understanding (which isn't much) is that your loot from fishing is now fixed, you can't change it. However is it possible to at least see what the loot you are trying to fish is, something like the Sonar potion in Terraria?
