### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by Crosshairs2** [Earthcomputer/clientcommands#537]
Clientcommands for the 1.20 version are crashing my game. I have gotten the error "exit code 1" and I am aware that it is sometimes caused by mods crashing the game. I have deleted client commands and used the other mods I was using and the game worked just fine. please fix it soon.

**Comment by Earthcomputer** [comment]
Log please

**Comment by Earthcomputer** [comment]
Closing due to no response
