### ISSUE TITLE
Progress on crack for enchantprediction

### ISSUE THREAD

**Issue by DarkAndromeda31** [Earthcomputer/clientcommands#54]
This could be a problem with my understanding but is there any way to see the progress of the in enchantment table cracker. To my understanding you put in random items into the table without enchanting or changing the number of books. Is this the correct method? I know about /ccrackplayerrng but I would like to use this on a server.

**Comment by Earthcomputer** [comment]
The clientcommands enchantment table cracker is so fast that it doesn't need a progress bar - it's done already ;P
By the way, `/ccrackrng` works on servers, on the 1.14.4 version of the mod.

**Comment by DarkAndromeda31** [comment]
Oh, I forgot to mention i was using the "clientcommands-1.12-20190126-snapshot" version. I tried to follow the advice in https://github.com/Earthcomputer/clientcommands/issues/21#issuecomment-495492904 but the GUI never seems to change when I either put random items into the table or enchant items, changing bookshelf counts in between.  Sorry for the hassle

**Comment by Earthcomputer** [comment]
Okay so without `/ccrackrng` you have to use the enchantment table.
1. `/ctemprule set enchantingPrediction true`
2. Do a dummy enchant
3. Put different items into the enchantment slot, without enchanting, and try different numbers of bookshelves until you have the 8-hex-digit XP seed (in the top left of the enchant table GUI).
4. Repeat steps 2 and 3 once more.
5. Now you are ready to do `/cenchant`. After executing the `/cenchant` command, wait for it to finish throwing items, and follow the instructions it gives you in chat.

**Comment by DarkAndromeda31** [comment]
Thanks I will try that now. <3

**Comment by DarkAndromeda31** [comment]
![image](https://user-images.githubusercontent.com/24707276/63571131-adb29500-c5c2-11e9-8cd1-60608562c988.png)
Unfortunately after finding my current seed though the Enchantment Cracker application while enchantprediction was set to true nothing happened on the UI. Is there some part of the UI that I am missing? Such as [here](https://youtu.be/Bl2lan-44H8?t=103) on the right hand side?
