### ISSUE TITLE
I'm on 1.20.1 and when I try to enchant with enchants like thorns and others, it says "cannot enchant item. will take too long or impossible." how do I fix this?

### ISSUE THREAD

**Issue by xAppl3zYT** [Earthcomputer/clientcommands#545]
also theres no fishing rng cracking

**Comment by YiYang-oa** [comment]
Me,too.

**Comment by YiYang-oa** [comment]
Because cfish was moved in 1.20.1.

**Comment by Earthcomputer** [comment]
In the enchanting table, thorns is only available on chestplates. I have now changed the `/cenchant1 command to not suggest thorns for other items, along with similar cases like this.
