### ISSUE TITLE
Game Crash on Quilt when used with Sodium and ViaFabricPlus

### ISSUE THREAD

**Issue by ugackMiner53** [Earthcomputer/clientcommands#547]
**Game Version**: Minecraft 1.20.1
**Loader Version**: Quilt 0.19.2

**Mod List**:
- Quilted Fabric API `7.0.5+0.84.0-1.20.1`
- Client Commands `2.8.2`
- Sodium `0.4.10+build.27`
- ViaFabricPlus `2.7.7`

When starting the game with *specifically* all three of the mods (besides QSL/QFAPI), the game will crash with the attached crash report.
If one of the three are disabled, the game will start fine.

Please see attached crash report for details:
[crash-2023-07-03_14.48.43-client.txt](https://github.com/Earthcomputer/clientcommands/files/11940272/crash-2023-07-03_14.48.43-client.txt)

Because the stacktrace begins with clientcommands compatibility, I'm assuming that it might be an issue here, but if not, let me know so I can possibly report it to Quilt!

**Comment by Finoway** [comment]
Hi, I have the same problem but with [3d skin layers](https://github.com/tr7zw/3d-Skin-Layers).

**OS:** Debian GNU/Linux 12 (bookworm) x86_64 
**Game Version:** Minecraft 1.20.1
**Loader Version:** Quilt 0.19.2


**Mod List:**

- Quilted Fabric API `7.0.6_qsl-6.0.4_fapi-0.85.0_mc-1.20.1`
- Client Commands `2.8.2`
- 3d Skin Layers `1.5.4-mc1.20.1`
- ViaFabricPlus `2.7.8`

Here's the crash report if it helps 
[crash-2023-07-16_20.28.29-client.txt](https://github.com/Earthcomputer/clientcommands/files/12064800/crash-2023-07-16_20.28.29-client.txt)

**Comment by Earthcomputer** [comment]
It looks like Quilt is registering client-side commands on game startup rather than when joining the world. This is a terrible idea.

**Comment by ugackMiner53** [comment]
### Update
I'm not sure if it was an issue on Sodium's end, or if version `2.8.3` fixed it, but Sodium now works with ViaFabricPlus and clientcommands, which fixes my issue. Unfortunately for Finoway, 3d Skin Layers appears to still have the same issue.

As for the underlying cause, I can't quite figure out why, but [this line](https://github.com/Earthcomputer/clientcommands/blob/65838103eb6cbd12e233d7345ef89ca8c1c314e4/src/main/java/net/earthcomputer/clientcommands/MultiVersionCompat.java#L204) in `MultiVersionCompat.java` is always returning `null` when called with the mod, and instantly crashes (because trying to invoke a function on an instance of null obviously fails).
```java
Object instance = itemReleaseVersionMappingsInstance.get(null);
```

Changing the function to check for null and return false if the instance isn't found fixes the crash, but obviously isn't ideal because it *could* affect the autocomplete for `/cenchant`. Unless there's a way to figure out why the line is returning null, it might make sense to add it so that if it fails, it just removes this compatibility layer instead of crashing.
```java
Object instance = itemReleaseVersionMappingsInstance.get(null);
if (instance != null) {
    return (Boolean) itemReleaseVersionMappingsContains.invoke(instance, item, getVersionEnum());
} else {
    return true;
}
```

**Comment by Earthcomputer** [comment]
As I said, the root cause of the issue is that client-side commands are being registered on game startup. I don't know why it only happens when Sodium <2.8.3 or 3d skin layers is installed, it looks like it should happen all the time with Quilt.

I think this is a Quilt issue, registering client-side commands without a world is a very bad idea and I don't know why they do it.

**Comment by Earthcomputer** [comment]
Maybe @FlorianMichael has some insight why the item release version mappings instance is only null outside of a world if Sodium <2.8.3 or 3d skin layers is installed?

**Comment by florianreuth** [comment]
I have absolutely no idea, this should never happen, the mappings class instances are created after Minecraft is completely loaded, I can't load them earlier because I use the Minecraft registries.

**Comment by Finoway** [comment]
Hello, I was redoing my minecraft instance. There is still the problem nobody has a solution ?
