### ISSUE TITLE
Can't start game on 1.20.1 (RuntimeException)

### ISSUE THREAD

**Issue by TG310** [Earthcomputer/clientcommands#548]
**Game Version:** Minecraft 1.20.1
**Loader Version:** Fabric 0.14.21
**Mod List:**
- Fabric API 0.85.0+1.20.1
- Client Commands 2.8.2

**Logs:**  [crash-2023-07-05_13.17.47-client.txt](https://github.com/Earthcomputer/clientcommands/files/11960064/crash-2023-07-05_13.17.47-client.txt)

**Comment by Earthcomputer** [comment]
We don't support cracked launchers here. Buy the game.
