### ISSUE TITLE
Crash with Replay mod

### ISSUE THREAD

**Issue by LoganDark** [Earthcomputer/clientcommands#55]
1. Join a server with recording on
2. Do stuff
3. Leave
4. Go to Replay Viewer
5. Double-click the replay you just made
6. After it loads press Escape

https://paste.dimdev.org/zedetejugi.mccrash

**Comment by hube12** [comment]
this issue is known and is fixed in my fork 
https://github.com/hube12/clientcommands/commit/81c6c5a25a85607769e006581c511f6151fa696c

**Comment by hube12** [comment]
this is due to the menu being a bit smaller

**Comment by LoganDark** [comment]
Then maybe OPEN A PR? Please?

**Comment by Earthcomputer** [comment]
1.12 is not supported anymore, sorry.

**Comment by LoganDark** [comment]
Hooly shit dude. Guess I'm using the fork then. 🖕

**Comment by Earthcomputer** [comment]
Calm down. It is normal to drop support for old versions of software. This is my hobby, it has to be fun. Backporting everything to 1.12 is not fun.

**Comment by LoganDark** [comment]
Well, the mod does what I need it to do. I'm not mad or anything, just appalled.

**Comment by Earthcomputer** [comment]
Be appalled all you like, but remember I'm not being paid ;)
