### ISSUE TITLE
Individual Port to Forge

### ISSUE THREAD

**Issue by Type-32** [Earthcomputer/clientcommands#556]
Hi I just wanted to ask whether if it is possible to port this mod to forge for personal use.

(Not like whether if it is possible to port this mod from Fabric to Forge, but more of whether the act of porting this mod will get me copyright striked or not)

**Comment by Gaming32** [comment]
This mod is licensed under LGPLv3, so copyright-wise, you are perfectly allowed to port to Forge, as long as you obey the license.
