### ISSUE TITLE
Error 255 right after Minecraft starts up

### ISSUE THREAD

**Issue by ART-007-25** [Earthcomputer/clientcommands#558]
[crash-2023-08-09_22.01.19-client.txt](https://github.com/Earthcomputer/clientcommands/files/12308099/crash-2023-08-09_22.01.19-client.txt)
On macOS – Prism Launcher (no, not cracked). Minecraft 1.20.1. Java 17. Both the CC mod and Fabric API mod are up-to-date, at least as far as I know. They are the only two mods enabled.

**Comment by Cyclopropinon** [comment]
same here with ubuntu 22.04lts

**Comment by Earthcomputer** [comment]
I can't reproduce this with the following, which is the same except for the OS as what you have:
- Prism Launcher 7.2
- Minecraft 1.20.1
- Fabric Loader 0.14.22
- Fabric API 0.86.1+1.20.1
- clientcommands 2.8.3
- Java 17
- Void linux

**Comment by Franck-Nein** [comment]
Same with Ubuntu 20.04.
Also, same issue when using MultiMC.

**Comment by Earthcomputer** [comment]
When you say you have the same issue, could you also send the crash log?

**Comment by Cyclopropinon** [comment]
nah, i found the culprit: sodium 0.5
i downgraded it and it worked fine
i seems to be incompatible with most of my mods

**Comment by Cyclopropinon** [comment]
logfile is buried somewhere, lemme recreate it

**Comment by Earthcomputer** [comment]
I don't think this is related to clientcommands
