### ISSUE TITLE
ctemprule is not working

### ISSUE THREAD

**Issue by IamLokYourDoor** [Earthcomputer/clientcommands#560]
When I want to turn on enchantment prediction, I cannot type ctemprule, then I started to find it in the command list, well, nothing.

**Comment by IamLokYourDoor** [comment]
When I want to turn on enchantment prediction, I cannot type ctemprule, then I started to find it in the command list, well, nothing.

**Comment by Earthcomputer** [comment]
It was changed to `/cconfig`
