### ISSUE TITLE
Corrupted config crashes the game on startup

### ISSUE THREAD

**Issue by mgsmath** [Earthcomputer/clientcommands#562]
[latest.log](https://github.com/Earthcomputer/clientcommands/files/12380561/latest.log)

**Comment by Earthcomputer** [comment]
Hi, can you please send the crash report? This log doesn't contain any sign of a crash.

**Comment by mgsmath** [comment]
[crash-2023-08-18_15.46.49-client.txt](https://github.com/Earthcomputer/clientcommands/files/12380590/crash-2023-08-18_15.46.49-client.txt)

**Comment by mgsmath** [comment]
when i removed client commands config file it works
