### ISSUE TITLE
Suggestion: Have UI screenshot on github/wiki

### ISSUE THREAD

**Issue by DarkAndromeda31** [Earthcomputer/clientcommands#57]
While trying to use the enchantmentpredictor I had no idea whether it was working as intended as after finding my seeds through the desktop application the mod interface had still not changed. What is the intended UI meant to look like.
![image](https://user-images.githubusercontent.com/24707276/63571131-adb29500-c5c2-11e9-8cd1-60608562c988.png)
Version - clientcommands-1.12-20190126-snapshot
*sorry to bother you again*

**Comment by Earthcomputer** [comment]
That is what the UI is meant to look like for crack state = uncracked. To get into crack state = cracked you have to follow instructions 1-4 that I gave you. If that's doing nothing then it could be a bug (although I've never encountered it before), but since you're using an old unsupported version of clientcommands, that bug isn't going to be fixed.

**Comment by DarkAndromeda31** [comment]
Ok thanks is there a current version for 1.12 or is 1.14 the only currently supported version? I performed the steps required to manually find the seed so I think its a bug.

**Comment by leumasme** [comment]
The Mod and the Desktop Application are independent from each other. You can use either to get the Enchant seed or Player seed and either to calculate the required item drops and Bookshelfs.
The mod can do both faster. not sure what you are missunderstanding here.

**Comment by DarkAndromeda31** [comment]
> The Mod and the Desktop Application are independent from each other. You can use either to get the Enchant seed or Player seed and either to calculate the required item drops and Bookshelfs.
> The mod can do both faster. not sure what you are missunderstanding here.

I used the desktop application while the mod was enabled and it did not find the seed after I used the method specified by the desktop application
