### ISSUE TITLE
Enchantment seed appears to be incorrect

### ISSUE THREAD

**Issue by PurPur134** [Earthcomputer/clientcommands#572]
After using `/ccrackrng`, the enchantment seed appears to be incorrect. It thinks I have a different enchantment seed than the one I appear to have. I don't what could be causing this because this is a vanilla multiplayer server and this has worked before and in testing worlds.
Here are some screenshots. Notice that the enchantments listed in the top-left are incorrect.
![2023-10-02_19 33 18](https://github.com/Earthcomputer/clientcommands/assets/139658227/21cd24f2-fb77-4a90-b4c8-2f2e2e77b1db)
![2023-10-02_19 34 39](https://github.com/Earthcomputer/clientcommands/assets/139658227/6a103cfa-5858-41a2-afe4-7faf2453a8fe)
![2023-10-02_19 34 40](https://github.com/Earthcomputer/clientcommands/assets/139658227/ac3e9700-0429-45be-8d9d-e5fcaaf5fb4a)
![2023-10-02_19 34 41](https://github.com/Earthcomputer/clientcommands/assets/139658227/60ae85bb-d4f8-4fbb-a385-55ee3deaa844)

**Comment by Earthcomputer** [comment]
If you are suspicious that `/ccrackrng` is producing the wrong result, you can get your XP seed if you're opped on the server using `/data get entity @s XpSeed`.

**Comment by PurPur134** [comment]
Unfortunately I'm not opped. Should I try the deprecated enchant cracker and see if that works?

**Comment by Earthcomputer** [comment]
Can you try it on a server where you are opped?

**Comment by PurPur134** [comment]
I tried it and the enchantments and `XpSeed` were both wrong.

**Comment by Earthcomputer** [comment]
Did you test the `XpSeed` immediately after running `/ccrackrng`, or after running `/enchant` as well?

**Comment by PurPur134** [comment]
After running `/cenchant` and doing a dummy enchantment (the XP seed in the top left only shows after you do that). In the player data it's stored as a decimal, but when converted to hexadecimal it was not the same seed.

**Comment by Earthcomputer** [comment]
1. Run `/cconfig clientcommands enchantingPredication set true`.
2. Run `/ccrackrng`
3. Do an enchantment

It should show now, and should be the same if all goes well. I am trying to determine if the bug is with `/cenchant`.

**Comment by PurPur134** [comment]
Yes, it worked, thanks! The XP seed is shown in the top-left and is the same as in the player data. I have no idea what could be causing this though.

**Comment by Earthcomputer** [comment]
Okay so that means bug is with `/cenchant`. It must be somehow throwing the wrong number of items, or else mispredicting how many random calls it would take. It's a bit tedious, but can you try to throw the items manually instead? You can use `/cenchant --simulate` to show how many items you need to throw without automatically throwing them.

**Comment by Earthcomputer** [comment]
Note that when throwing items manually, you must throw each item individually, you cannot throw out a stack at a time, that doesn't work.

**Comment by PurPur134** [comment]
Throwing the items manually did work and gave the correct enchantments. Also, could you explain how `/cenchant` works? I don't get how throwing items would affect the enchantment seed.

**Comment by PurPur134** [comment]
Hello, any updates on this?

**Comment by Earthcomputer** [comment]
I haven't looked into fixing it yet. Throwing items changes the player RNG, which is also used to generate the XP seed. It doesn't affect the current XP seed, only from the next one that is generated, which is why you typically need to do a dummy enchant.

**Comment by Earthcomputer** [comment]
Hi there, sorry for the delay. I believe I have fixed this in https://github.com/Earthcomputer/clientcommands/commit/e7b9ec1fe526571d026603fac29894ed138cfab1. Could you try out the [new build](https://github.com/Earthcomputer/clientcommands/actions/runs/8132593046/artifacts/1293133620) and let me know if it works?

**Comment by Earthcomputer** [comment]
Going to assume it's fixed. We can always reopen later if it's not.

**Comment by Realzhazha** [comment]
> Going to assume it's fixed. We can always reopen later if it's not.

I am playing 1.20.4, is there any possible ways to fix this on earlier versions?

**Comment by Earthcomputer** [comment]
I don't create releases for older versions except for security updates or critical loss of function. You can use the latest version with ViaFabricPlus to connect to older servers
