### ISSUE TITLE
Failed to Crack Seed

### ISSUE THREAD

**Issue by Crosshairs2** [Earthcomputer/clientcommands#575]
It will not crack the RNG on my Minecraft server, but it works fine on my single player world. It is not modded, but it has the warp and life steal plugin. Can you please fix this?

**Comment by Earthcomputer** [comment]
You just wrote two contradictory statements:
- It is not modded
- it has the warp and life steal plugin

**Comment by Crosshairs2** [comment]
Correction: the server is not modded, but my client is, and using this has 100% worked before. also, i played on this server with the same plugins on a different version and it still worked, which leads me to believe that it is a problem with this version of the mod, and nothing I'm doing. @Earthcomputer
