### ISSUE TITLE
Failed to crack player seed

### ISSUE THREAD

**Issue by Crosshairs2** [Earthcomputer/clientcommands#576]
It will not crack the RNG on my Minecraft server, but it works fine on my single player world. the server is not modded, but my client is, and using this has 100% worked before. also, I played on this server with the same plugins on a different version and it still worked, which leads me to believe that it is a problem with this version of the mod, and nothing I'm doing. The plugins are warps and lifesteal. Can you please fix this?

**Comment by Earthcomputer** [comment]
The server is probably running Paper. There is no workaround for this.
