### ISSUE TITLE
Allow commands to bypass minecraft chat limit

### ISSUE THREAD

**Issue by Schlagbul** [Earthcomputer/clientcommands#579]
I'd like to be able to type infinitely long commands especially for /cgive or /cenchant while I have seen that it was marked as completed at one point I don't believe it applies to the current version, in my opinion it would be even better if the client allowed you to disable the limit on just client commands but all commands instead.

**Comment by Earthcomputer** [comment]
It's not possible to remove the limit on all commands

**Comment by Schlagbul** [comment]
While I know it is a server side thing, I just want a way to bypass the client side limit where it stops you from typing.

**Comment by Catsef** [comment]
Can do with mods

**Comment by Earthcomputer** [comment]
This used to be a feature, I think it got removed when clientcommands was ported to fcapi. I just readded it though.
