### ISSUE TITLE
Unknown Action does not cancel RNG Cracking Status clientside, but progresses Seed Serverside

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#58]
You seem to have missed an action wich progresses the RNG Seed.
https://streamable.com/49q48
As partly seen in the video, i was using an Unbreaking 1 Gold Pickaxe with Infinite Tools Enabled and the Player RNG Cracked. This had worked mostly fine for over 30 minutes, until i had to make a new iron pickaxe to get some gold. After Smelting Iron, crafting a Pickaxe and getting the gold, i wanted to continue mining with the Gold Pickaxe, without recracking my rngseed as i had not gotten the notification that it had to be restarted. The gold pickaxe unexpectedly broke after a few blocks.

I dropped items during this, but i assumed that it would not break it as i did not get a chat message.

**Comment by Earthcomputer** [comment]
I didn't see it in the clip, but while playing around I was able to cause such a desync by having items being thrown due to exiting a crafting GUI while my inventory is full. Do you think while smelting iron and crafting you may have done this?

When the player RNG is cracked, clientcommands is supposed to take into account item throws (for your convenience). I guess if you throw an item out this way it doesn't detect that for some reason.

**Comment by Earthcomputer** [comment]
Oh, by the way, there is a TempRule `playerRNGMaintenance` which defaults to true, which you can use to turn off this "auto-correction" from item throws, so that you can see whether it detected the item throw.

**Comment by leumasme** [comment]
is it technically possible to also maintain the rng on events like particles? it would be a massive upgrade to not loose rng when sprinting etc @Earthcomputer

**Comment by leumasme** [comment]
Additionally, checking if the velociy of the dropped Items matches the expectation may alert of Desynced RNG, but i am not sure if this is possible if the player is rotating the head while the items are being dropped.
Also alert the user if the item unexpectedly takes damage with infiniteTools enabled.

**Comment by Mhowser** [comment]
Pardon me, but what is this infinitetools you are talking about?

**Comment by Earthcomputer** [comment]
Unfortunately many of the actions that are timing dependent cannot be reliably simulated on the client, for example sprinting. The number of RNG calls depends on the number of ticks you were sprinting serverside, which may be different from the number of ticks you were sprinting clientside. And the problem gets worse if the server or the client is lagging.

There is another category of calls which I could detect and simulate on the client, but detecting this stuff on the client would add so much more complexity to the already complex detection code that I decided it would not be worth it. One thing that is worth it however is simulating eating, see #65.

**Comment by leumasme** [comment]
@Mhowser 
/ctemprule set infiniteTools true
If your player RNG is cracked ( /ccrackrng ), this will manipulate Unbreaking randomness by dropping items, so that you will never actually use durability.

**Comment by Mhowser** [comment]
Wow, that is handy. Thanks!

**Comment by Earthcomputer** [comment]
~~It looks like this is due to an `isClient` check inside `PlayerContainer.close` which I had not taken into account.~~
It looks like a more general problem with container closes not being simulated clientside
