### ISSUE TITLE
/cghostblock replace functionality

### ISSUE THREAD

**Issue by Subortinaiti** [Earthcomputer/clientcommands#581]
## Syntax
/cghostblock replacefill [x] [y] [z] [x] [y] [z] blockID] [blockID]
/cghostblock replaceset [x] [y] [z] blockID]

## Description
allows the player to replace only a certain block with ghostblocks, using the /ghostblock command.

**Comment by Earthcomputer** [comment]
https://github.com/Earthcomputer/clientcommands/pull/585
