### ISSUE TITLE
Confused with /cenchant's output.

### ISSUE THREAD

**Issue by UnixTMDev** [Earthcomputer/clientcommands#583]
I crack the player RNG, I do the enchantment manipulation, but then I get stuck here:
```
Your enchantment seed is ready
Bookshelves needed: 8
In slot: 3
```
I don't know what it means by bookshelves needed and `in slot`. Could someone who knows please clarify?

**Comment by Gaming32** [comment]
You need 8 bookshelves around your enchanting table, and your selected enchantments are available in the third slot of the enchanting table.

**Comment by UnixTMDev** [comment]
Ahhhh ok. Thanks!
