### ISSUE TITLE
/cenchant incorrectly identifying featherfall IV even though it says it does 1.20.4 Version 2.8.9

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [Earthcomputer/clientcommands#586]
This has happened multiple times in a row so I know this isn't a one time thing

https://github.com/Earthcomputer/clientcommands/assets/86382621/4b1a46c1-a6e3-4c7f-9c27-e5ec2aaf5b17

**Comment by bendy1234** [comment]
you need to lower the amount of bookshelfs around the enchanting table to the needed amount. Most of the times you don't need to but feather falling has a lower chance of showing up at lvl 30.
