### ISSUE TITLE
Enchantprediction may fail on low tps servers

### ISSUE THREAD

**Issue by Ethan-Vann** [Earthcomputer/clientcommands#6]
when using enchant prediction on low tps servers it appears that if it cant read the enchants fast enough it fails causing invalid seed, this can ovb be fixed by using the standalone ench cracker but is still a bug in the client version

**Comment by Earthcomputer** [comment]
I'll check this

**Comment by Ethan-Vann** [comment]
after trying some more cases it looks like it's not about not being able to read the first enchants fast enough I think if the item in the table doesn't update immediately it fails because it reads the same enchants again, maybe some logic to prevent updating until the item is taken out of the table could fix this

**Comment by Earthcomputer** [comment]
You mean you place an item into the table, a certain set of enchantments come up, then replace it with another item and it reads from the old enchantments before they disappear?

**Comment by Ethan-Vann** [comment]
it seems to read the enchants twice on the same item once before the enchant and once after. but looking at the code I don't see a case where this can happen.

**Comment by Ethan-Vann** [comment]
this looks like it's just an incompatibility on multiplayer servers running papermc and potentially spigot tested and got invalid on local papermc server running 20tps. you can close this now

**Comment by Earthcomputer** [comment]
Thanks. I would have suspected that papermc would have protection against enchanting manipulation.

**Comment by Ethan-Vann** [comment]
I don't think it's intentional at least I can't find anything in their commits or patches to suggest that. Its probably a side effect of another change they make
