### ISSUE TITLE
Manipulation of RNG Block Drops, like Lapis, Redstone, Other ores with Luck Enchantment

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#60]
I do not know if this is possible as i am not sure if this depends on the player rng, but manipulating RNG drops of blocks, like Lapis, Redstone, Melons, and other blocks like Diamonds and Coal when using the Luck Enchantment to always drop the maximum possible amount would be a great feature.

**Comment by Earthcomputer** [comment]
Not possible, different RNG. It is possible by building a serverside contraption to control the world RNG, but that gets considerably more complicated in 1.13+, and probably not worth it.
