### ISSUE TITLE
I cannot find ctemprule command

### ISSUE THREAD

**Issue by Fyphen1223** [Earthcomputer/clientcommands#602]
Literally, I cannot find ctemprule commands in my MC. It's Fabric 1.20.2.

**Comment by Fyphen1223** [comment]
#520 
Sorry, I found that :(

**Comment by Earthcomputer** [comment]
It's `/cconfig` now. Where did you find to use `/ctemprule`, so we can update the tutorial or whatever it is?

**Comment by R4z0rX** [comment]
Probably the [Wiki](https://github.com/Earthcomputer/clientcommands/wiki/cenchant).

**Comment by Earthcomputer** [comment]
Gotcha, I've updated the wiki

**Comment by Fyphen1223** [comment]
Thank you so much everyone :)

**Comment by Fyphen1223** [comment]
Wait I didn't mention a correct issue lmao

**Comment by Fyphen1223** [comment]
Well, thanks, I close this issue!
