### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Bipbip2109** [Earthcomputer/clientcommands#605]
![Scan1](https://github.com/Earthcomputer/clientcommands/assets/88253359/0ded9b59-18c9-4b19-a453-a81cb07a2bda)
While launching the game with the latest windows 11 insider preview, this mod and show-me-your-skin were both flagged as containing the trojan "Trojan:Script/Wacatac.B!ml", probably a false positive but we never know

A similar issue was posted by myself on https://github.com/enjarai/show-me-your-skin

**Comment by Gaming32** [comment]
Antiviruses are pretty bad at Java. There is no malware in clientcommands (provided you download it from an official source, like Modrinth). If you don't trust it, you can review the source code and build it yourself.

**Comment by Earthcomputer** [comment]
There is nothing I can do about Window's shitty antivirus detection, so I don't know why you're even reporting it to me. Report it to Windows and be done with it.

**Comment by Earthcomputer** [comment]
But like Gaming said, make sure you downloaded it from an official source, such as GitHub or Modrinth. There are shady sites such as 9minecraft that rehost mods and insert malware into them.

**Comment by Bipbip2109** [comment]
Downloaded it from modrinth, just thought that it was strange that 2 mods were flagged at the same time

**Comment by Earthcomputer** [comment]
Yeah nothing I can do about it sorry.
