### ISSUE TITLE
Show progress bar when throwing items

### ISSUE THREAD

**Issue by nayfaan** [Earthcomputer/clientcommands#612]
building upon #54, would like to see commands like /cenchant to show the progress bar in chat when throwing items to reach a certain seed. From my experience, some could throw items for more than 5 minutes. Would be nice if there's a progress bar in chat to show us the progress

And to further enhance that, it'd be great if a notification bell sound could be played (perhaps toggleable in config) when all items have been thrown and the seed has been reached. This would allow the player to be more AFK.

**Comment by m-sarabi** [comment]
Like the progress bar idea. The bossbar could work well for this.
