### ISSUE TITLE
List Gamerules with `/cgamerule` command

### ISSUE THREAD

**Issue by m-sarabi** [Earthcomputer/clientcommands#616]
This feature request assumes the server sends information about gamerules to the client. It proposes adding the following commands:

- `/cgamerule list (all|modified)`: lists all gamerules (or only modified ones) and their corresponding values.
- `/cgamerule query <rule>`: prints the value of the specified gamerule.

**Comment by Earthcomputer** [comment]
The server does not send a list of gamerules to the client.
