### ISSUE TITLE
This is probably not possible but...

### ISSUE THREAD

**Issue by Crosshairs2** [Earthcomputer/clientcommands#619]
My school's Minecraft server uses Bukkit plugins, and I was always able to use client commands before, but after 1.20 released, Clientcommads /ccrackrng has never worked. I was wondering if this is fixable, or if there is a version of the mod for 1.20.4 that can be used on Bukkit servers.

**Comment by Earthcomputer** [comment]
When you say "Bukkit" you are probably talking about Paper, in which case no.

**Comment by Crosshairs2** [comment]
I'm not talking about paper (Probably), since there is no Spigot or Paper plugins. Paper can run Paper, Spigot, and Bukkit, Spigot can run Spigot and Bukkit, and Bukkit can run only Bukkit plugins.

**Comment by xpple** [comment]
When you click `F3` it should show what software the server is running on. Note that Paper plugins definitely do exist.

**Comment by Earthcomputer** [comment]
Bukkit hasn't existed on its own since 1.7. You're either using Spigot, Paper, or one of their forks.

**Comment by Gaming32** [comment]
Actually CraftBukkit does still exist, but there's no official way to obtain a built copy. You have to either compile it manually or download it from shady prebuilt jar sites like getbukkit.

**Comment by MiniDigger** [comment]
(it's just a fork maintained by spigot, it's not the original craftbukkit from the Bukkit project, making a distinction between spigot and craftbukkit seems arbitrary)
