### ISSUE TITLE
Announce Item Drop Amount and Estimated Time Required when starting Enchantment Manipulation

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#62]
Enchanting a Perfect Sword can take ~10 minutes (wich is now finally possible with the max item calculation temprule), and it would be handy to know how long you have to wait while it drops items.

**Comment by Earthcomputer** [comment]
Also the option to not go for it would be nice

**Comment by leumasme** [comment]
Also Showing Level and Bookcase Cost earlier would be nice, and the option to continue searching for an XP-cheaper random.

**Comment by Earthcomputer** [comment]
![Image](https://i.imgur.com/SxU431a.png)
You can now use `/cenchant --simulate ...` to get this output rather than actually doing the manipulation.
To generate this one, I used `/cenchant --simulate bow with flame 1`
