### ISSUE TITLE
/cgive over 256 characters in length not executed properly

### ISSUE THREAD

**Issue by thecolonel63** [Earthcomputer/clientcommands#627]
While the chat box allows commands longer than 256 chars to be typed out, upon trying to execute a /cgive command longer than that it fails with a CommandSyntaxException at position 255, as the command gets cut off internally.

Command attempted: 

`/cgive minecraft:armor_stand{EntityTag:{NoBasePlate:1b,ShowArms:1b,ArmorItems:[{id:"leather_boots",Count:1b,tag:{display:{color:14935011}}},{id:"leather_leggings",Count:1b,tag:{display:{color:12566463}}},{id:"leather_chestplate",Count:1b,tag:{display:{color:16448250}}},{id:"player_head",Count:1b,tag:{SkullOwner:"thecolonel63"}}],HandItems:[{},{}]}}`

The only mods I'm running are ClientCommands 2.8.14 for 1.20.4 and Fabric API 0.97.0+ 1.20.4

While I've only tested it with /cgive, there's a pretty good chance this impacts other commands as well.

**Comment by Earthcomputer** [comment]
Please update to 1.20.5 and let me know if this still happens.

**Comment by RealRTTV** [comment]
Just confirmed in a dev env on 1.20.5, working on a patch now. Additionally, a paste is cut off when the chat field does not already start with a command.

**Comment by RealRTTV** [comment]
just fixed the weird cutoff issue by refactoring the EditBox code
