### ISSUE TITLE
Compatibility issues with SeedCrackerX

### ISSUE THREAD

**Issue by E0x72-21** [Earthcomputer/clientcommands#630]
The fabricloader will prompt that Client Commands 2.8.14 are incompatible with SeedCrackerX when the game starts.

**Comment by crosby-moe** [comment]
yes that is on purpose https://github.com/Earthcomputer/clientcommands/commit/6023f2f7a9a0d6e057019043d8a924355855860a

**Comment by crosby-moe** [comment]
it would be better to open an issue on their side, as that is where the incompatibility seems to be
