### ISSUE TITLE
Sweeping edge 3 not working with client commands 1.14.4

### ISSUE THREAD

**Issue by Rolandsteele** [Earthcomputer/clientcommands#64]
Ended up trying sweeping edge in game, and uh, less than desirable results using clientcommands. Attempted it multiple times on a book, got lure a couple times. Not sure how that might be happening, but figured it was worth documenting.

**Comment by Earthcomputer** [comment]
Are you talking about getting it on an item, or its functionality?

**Comment by leumasme** [comment]
Can not confirm for directly enchanting swords.
While it took 4 tries for unknown reasons (probably server lag desyncing clientside/serverside dropped items) and waiting 3-10 minutes between every try for cracking to drop the items, i got this sword in one enchant on a spigot 1.14.4 multiplayers server.

![image](https://user-images.githubusercontent.com/29953391/63757336-2d3dae00-c8ba-11e9-95f5-c07e5b9606a1.png)

**Comment by leumasme** [comment]
@Earthcomputer From him saying he gut Lure instead, pretty sure that he is trying to Enchant a book, but is getting different enchants than predicted

**Comment by Earthcomputer** [comment]
@Rolandsteele are you by any chance connecting to a 1.14-1.14.2 server via https://github.com/Earthcomputer/multiconnect?

**Comment by Rolandsteele** [comment]
Nah, it's just a 1.14.4 server, whitelisted.

**Comment by Earthcomputer** [comment]
Can you give some steps to reproduce?

**Comment by Rolandsteele** [comment]
Alright, well. Spigot server, no paper, everything else is functional clientcmd wise. 15 bookshelf exposure, did a diamond sword with unb 3 sharp 4 fire 2 knock 2 looting 3. Then I followed up with an enchant on a book for sharp 4 sweeping 3. Ended up not being what I wanted, so I just recracked, and tried the sweeping 3 only on a book. Ended up with lure.

**Comment by Earthcomputer** [comment]
I'm unable to reproduce this on a vanilla 1.14.4 server. Also note that while enchanting books you have to be extra careful to expose the exact correct number of bookshelves it tells you in chat. Always using 15 may result in the incorrect enchantments.
