### ISSUE TITLE
/cenchant error.  Impossible or it will take too much time to get these enchantments

### ISSUE THREAD

**Issue by MIIIdav** [Earthcomputer/clientcommands#646]
I downloaded this mod for version **1.20.1**, that is, **2.8.5** version of this mod. When I want to enchant an item that is not currently in the enchantment table, I get an error - **Impossible or it will take too much time to get these enchantments**. If this is the case with my mods, then I can throw off the assembly, but I’ll say right away that I went through them, deleted some, but absolutely nothing.

Please help =(

**Comment by Earthcomputer** [comment]
Please update and use ViaFabricPlus. Normally I recommend using the latest version of clientcommands but since VFP isn't out for 1.21 yet, I recommend you use the 1.20.6 version of clientcommands and VFP.
