### ISSUE TITLE
Add support for Sinytra Connector?

### ISSUE THREAD

**Issue by LxyFreely** [Earthcomputer/clientcommands#652]
Add supprt for Sinytra Connector？Automatically disable some features to maintain compatibility with Sinytra Connector is understandable.

**Comment by Gaming32** [comment]
Does it not already work with Connector?

**Comment by Earthcomputer** [comment]
Mods don't need to "add support" for connector. They should just work. Please can you be more specific about what you tried and what isn't working?

**Comment by Uright-Xuqing233** [comment]
> Mods don't need to "add support" for connector. They should just work. Please can you be more specific about what you tried and what isn't working?

I tested it in 1.20.1, the command doesn't works well.

**Comment by uright008** [comment]
> Mods don't need to "add support" for connector. They should just work. Please can you be more specific about what you tried and what isn't working?

some features doesn't works well like cenchant

**Comment by Earthcomputer** [comment]
There was a crash with NeoForge that was fixed in the latest version

**Comment by stegpeng7** [comment]
> There was a crash with NeoForge that was fixed in the latest version

will the crash with NeoForge + Sinytra in the latest versions be patched? is it a Connector issue rather than a clientcommands issue?

**Comment by Earthcomputer** [comment]
@stegpeng7 please [search](https://github.com/Earthcomputer/clientcommands/issues/742) for issues before commenting on older ones

**Comment by stegpeng7** [comment]
@Earthcomputer my apologies, my message was made when i didn't have a strong connection and this issue was already loaded, and i was not able to search up other issues at the time.
