### ISSUE TITLE
command to automatically dump all stackable items into nearby containers

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#66]
This would Dump all stackable Items in the players Inventory (excluding hotbar?) into containers in the players reach if those containers already contain the item. 
optional parameter to keep searching for containers until manual stop.

**Comment by Earthcomputer** [comment]
I honestly don't think this would be very useful to very many people, I'm sure most people would want to stay more organized than dumping items into random chests.

**Comment by leumasme** [comment]
it would only add to the container if it already contains the item, allowing for quick dumping if your system is sorted, but you have decide.
