### ISSUE TITLE
[Sugestion] Allow client-side commands to bypass minecraft chat limit

### ISSUE THREAD

**Issue by Starmania** [Earthcomputer/clientcommands#660]
This is a follow-up of  #579 

> I'd like to be able to type infinitely long commands especially for /cgive or /cenchant while I have seen that it was marked as completed at one point I don't believe it applies to the current version, in my opinion it would be even better if the client allowed you to disable the limit on just client commands but all commands instead.

I would add that it doesn't matter if the server doesn't receive more that 256 characters, as this is not intended to send bigger message to the server.

If you are ok, I could create a PR of this issue

**Comment by Earthcomputer** [comment]
This is already implemented, if it doesn't work then that's a bug
