### ISSUE TITLE
feather_falling enchantment still let cenchant unormal work

### ISSUE THREAD

**Issue by uright008** [Earthcomputer/clientcommands#662]
I've try for many times, and I followed the instructions in every step.If I enchant other enchantments, it works nice. But when I want to get a feather_falling enchantment, I always get something in other enchantments.

**Comment by uright008** [comment]
![image](https://github.com/user-attachments/assets/167bdc49-8c43-453a-9db2-59998fc2be25)

**Comment by uright008** [comment]
![image](https://github.com/user-attachments/assets/6228f2cb-6470-4560-874c-7b38d8b02f0a)

**Comment by Earthcomputer** [comment]
It says "bookshelves needed: 5" in chat but you've got 16 bookshelves. So you didn't follow the instructions

**Comment by uright008** [comment]
sry
