### ISSUE TITLE
Block/Entity Highlight Command

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#67]
This command would draw a colored semitransparent box at the entity/block hitbox.
This colored Box would be drawn above all other Blocks/Entities, so it is seen even if obstructed.
You could then add a clickevent to cfind / cfinditem / cfindblock, wich highlights the block/entity found.

**Comment by Mhowser** [comment]
Could it use the vanilla spectral effect?

**Comment by Earthcomputer** [comment]
I just added `/cglow` for entities.

**Comment by Earthcomputer** [comment]
I think the spirit of the block request is pretty much covered by #78 and #79, so I can close this issue now.
