### ISSUE TITLE
Question: Usage of exactly option in the cenchant command

### ISSUE THREAD

**Issue by EnderGZM** [Earthcomputer/clientcommands#670]
I have a question regarding the cenchant command, specifically about the exactly option. Could you please provide guidance on how to correctly use this option?

Any example or additional details would be greatly appreciated. Thank you in advance for your help!

**Comment by Earthcomputer** [comment]
It just prevents any additional enchantments from happening other than the ones you specify

For example
```
/cenchant diamond_sword with sharpness 4 exactly
```
will enchant a diamond sword with sharpness 4 and make sure it has no additional enchantments
