### ISSUE TITLE
A command to get NBT data of entities

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#68]
Alternatively, Copy to Clipboard instead of Showing.

**Comment by Earthcomputer** [comment]
Why would you need this exactly?

**Comment by leumasme** [comment]
Ex. Getting Info (Durability, Enchants, Curses, Name) about Items equipped on Players / Monsters,
Getting Villager NBT to get the Coordinates of their Workstation,
Getting Animals/Villagers Age to see when they grow up,
Finding NBT Tags to filter by when using cfind (ex. Finding the NBT for Mobs in a Raid to find all Raiders) without starting a singleplayer world, reproducing the scenario and using the data command.

**Comment by Earthcomputer** [comment]
I think this would best fit as a new, separate command, like `/cgetdata` or `/cgetnbt`. However, users of this command, and of `/cfind @e[nbt=...]` will have to realize that not all of the NBT data of entities is accessible on the client - it may still show NBT values but may be incorrect.

**Comment by Earthcomputer** [comment]
Added `/cgetdata` to get client-side NBT data for block entities and entities.

**Comment by Mhowser** [comment]
Changed your mind?
