### ISSUE TITLE
cfinditem: Wildcard Search // Allow Tags

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#69]
For those moments that you want all types of ore or all types of some wood item.
* stands for any string; ? stands for any single character

**Comment by leumasme** [comment]
github markdown. i ment * stands for any string

**Comment by Earthcomputer** [comment]
You should already be able to use [Tags](https://minecraft.gamepedia.com/Tag) for this purpose.

**Comment by leumasme** [comment]
![image](https://user-images.githubusercontent.com/29953391/64070085-b574d800-cc59-11e9-9911-559126e6a0cb.png)

**Comment by Earthcomputer** [comment]
Well, that should be changed :D

**Comment by Earthcomputer** [comment]
By the way, you can search for multiple items at once, as multiple `/cfinditem --keep-searching` commands can run at the same time.

**Comment by Earthcomputer** [comment]
Implemented tags.

**Comment by ModProg** [comment]
I'd be interrested in wildcards. i.e. search for anything iron (to also find blocks/ore) and would be interrested to implement that.

Should I open a new issue?

**Comment by Earthcomputer** [comment]
Perhaps you could open an issue for client-side tags
