### ISSUE TITLE
The cgive and ckit commands do not update the client inventory

### ISSUE THREAD

**Issue by haykam821** [Earthcomputer/clientcommands#693]

**Comment by Aesthir** [comment]
I have this problem as well. Used to work in 1.21.1, but no longer works for me in 1.21.3... I'm using fabric.

**Comment by crosby-moe** [comment]
yeah you need to set the itemstack in the inventory too now

**Comment by Aesthir** [comment]
Ahhh, thank you! I got it now. It makes an invisible item in your inventory, but if you use it, it still works. For my purposes, I make a player_head and have to place it on an armor stand, then remove it again to get the item.

**Comment by crosby-moe** [comment]
very odd that it makes an invisible item

this is what works for me: https://github.com/RacoonDog/meteor-client/blob/command-api-v2/src/main/java/meteordevelopment/meteorclient/utils/commands/CreativeCommandHelper.java#L36-L38

**Comment by Earthcomputer** [comment]
> very odd that it makes an invisible item

Yeah you have an extra `Inventory.setStack` call there on the client. It's a bit more annoying for me because it's the give command not the item replace command

**Comment by xpple** [comment]
I have reopened the issue as it still persists for the ckit command.
