### ISSUE TITLE
InfiniteTools not working on 1.21

### ISSUE THREAD

**Issue by Tost000** [Earthcomputer/clientcommands#699]
![изображение_2024-12-26_203652906](https://github.com/user-attachments/assets/b9eeb57e-8e31-4fb9-854b-ebc6f9d4ac5a)
The update says that infiniteTools works again after downloading the mod the mod started but I couldn't enable this function "/cconfig clientcommands infiniteTools set true " other functions worked what did I miss? I used "clientcommands-2.9.3.jar" and minecraft 1.21 fabric

**Comment by Earthcomputer** [comment]
In the same changelog it says
> Unbreaking manipulation is broken. It has been disabled for 1.21, but is still there for 1.20 and below.
