### ISSUE TITLE
cenchant: Enchants Started and Cancelled still send "Ench Seed Ready" message when enchanting.

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#72]
This can cause multiple messages to show at once after enchanting if you started multiple cenchants. Messages are not cleared by breaking rng status either

**Comment by Earthcomputer** [comment]
What do you mean by a "cancelled" enchant?

**Comment by Earthcomputer** [comment]
Is this still an issue with the new release, 2.3.5?

**Comment by leumasme** [comment]
This issue Directly was fixed, but it came with a new one.
Start a cenchant, let it Finish until it requests a Dummy, then Sprint.
The Enchant Seed message will show, as if you had done the dummy enchantment.
It will also show multiple times if you ran cenchant multiple times without doing anyhing in between.
After that, cenchant will return the <Impossible/Over maxCalculations> message, instead of the <Seed not Cracked> message. (As you just broke it by Sprinting.)

**Comment by Earthcomputer** [comment]
I cannot reproduce the enchant seed showing when you invalidate the seed by sprinting. However, I can reproduce two messages showing when you run the command twice. Can you give more detailed reproduction steps for the first issue?

**Comment by Earthcomputer** [comment]
Never mind, I have just managed to reproduce the first bug, that requires enchCrackState to be cracked.
