### ISSUE TITLE
/cfind Player Name Completion does not respect existing input

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#73]
Example:
Be on Server with Player123
Start typing the command:
/cfind Playe
Use the Arrow keys and Tab or your Mouse to Select the Suggestion for "Player123"
When Selecting the suggestion, the result will be
/cfind PlayePlayer123
Also, Tab Completion for Players that do not match the Existing input is still shown.

**Comment by Earthcomputer** [comment]
I believe this might be a vanilla bug

**Comment by Earthcomputer** [comment]
Fixed this, and a number of related issues.
