### ISSUE TITLE
Is ClientVirtualWorld still Planned?

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#76]
I remember you had planned a cvw command to quickly fire up the currently loaded World on a Sever as a gm1 Singleplayer, to quickly test new Builds and Ideas.
Is this still planned?

**Comment by Earthcomputer** [comment]
No. It was too buggy and would be better as a world download module, which would be better as a separate mod. Even then, the idea of downloading a world and expecting it to work the same is fundamentally flawed, as the client doesn't have the necessary information to simulate the world itself.

Also, this is a high volume of requests in a short space of time, and I can't handle them all fast enough. Could you maybe try to limit yourself to 1 request a day? That would be great :)

**Comment by leumasme** [comment]
sorry
