### ISSUE TITLE
command request: "/ccolorchat" or "/cchat color true"

### ISSUE THREAD

**Issue by Mhowser** [Earthcomputer/clientcommands#80]
![image](https://user-images.githubusercontent.com/24195572/64100316-39919300-cd20-11e9-96f1-a173f57c3095.png)

To put it simply, this command will enable the player to type the formatting character `§` in any text input area (think signs, chat, anvil). I think `/cchat` would be a better choice as it allows for better future-proofing and can be used for more potential chat utilities.

I am aware that multiplayer servers kick the client if a formatting code is sent to the server with "illegal characters in chat". Perhaps a warning could be displayed when the module is enabled, or when the player tries to send formatted text on a multplayer server.

What do you think?

**Comment by Earthcomputer** [comment]
As this doesn't work in multiplayer, and chat messages are generally intended for talking to other players, I don't really see much of a usecase. As for books, this was already a planned feature of another mod of mine, which is currently shelved but might be brought back and ported to 1.14. If I add that feature to anywhere, it will be that mod, not this one.

**Comment by Mhowser** [comment]
I asked someone else to make the color chat mod.
https://www.curseforge.com/minecraft/mc-mods/color-unchained
It's very nice, would have preferred ClientCommands had it.

**Comment by Earthcomputer** [comment]
I stand by my previous reasoning. Clientcommands is constrained by what's possible on a vanilla server. That mod you linked needs to also be installed on the server.
