### ISSUE TITLE
/cenchant not consistent on server

### ISSUE THREAD

**Issue by Rolandsteele** [Earthcomputer/clientcommands#81]
I'm messing around on this new server a few friends and myself started up recently, and I'm a bit confused as to why things are turning out inconsistently. I've isolated as many variables as I can, for whatever reason however, I don't get my intended results. Like when making a max bow, I instead managed to use a tier-3 enchant to get simply unbreaking 3 on it. Something to note is that I am running my set up near an active end portal, but I doubt that has any significance. The server is also running a few plugins, which I think is the most likely reason this isn't working, as the general server config is largely untouched. Anybody know if any of the following would break the process on a 1.14.4 server?

Worldedit
WorldGuard
PermissionsEx
Dynmap
DiscordSRV
Essentials
Treefeller+
EssentialsChat

I've used the exact same process in a vanilla world, and so far as I can tell, I should be getting perfect results so long as none of those plugins are actually interfering with my rng.

**Comment by Rolandsteele** [comment]
Couple of extra notes though, definitely not running Paper. I'm pretty sure they *started* using it at launch, but just fell back to spigot. Essentials version was running two versions behind.

**Comment by Earthcomputer** [comment]
Modded servers are not supported. Vanilla is very well supported so it's probably an issue with one of those plugins.
