### ISSUE TITLE
Option for cfindblock to only show exposed blocks

### ISSUE THREAD

**Issue by User670** [Earthcomputer/clientcommands#84]
Some servers have an anti-xray plugin that disguises blocks not exposed as random ores. On these servers, cfindblock (or any other block finding mods) might, say, "find" a diamond ore and then realize that said ore is not there once the player digs his way to that block.

I suggest an option for cfindblock to only show blocks that are exposed (on at least one side, or configurably one side/edge/corner) to air or transparent blocks.

~~clientcommands is soon becoming cheating tool~~
~~anti-clientcommands plugins when~~

**Comment by Earthcomputer** [comment]
I am hesitant to add a feature whose only clear use is for cheating on multiplayer servers.

Although there are other features in clientcommands that can be used for cheating, those same features can be used for other legitimate purposes which may interest (maybe a minority) of players, such as `/cbook` which can also be used to make broken portals. Even `/cfindblock` can be useful, I have found; you don't have to use it for `diamond_ore`. I've found `/cfindblock oak_log` helps when cutting down large oak trees. There are even some players that enjoy xraying on singleplayer.

But anti-cheat bypasses are a step too far across the line in my opinion. The only situation they are useful is on servers where they specifically don't want you to cheat in this way. So I'm afraid that's a no.
