### ISSUE TITLE
Request: A quiet personal one

### ISSUE THREAD

**Issue by TG310** [Earthcomputer/clientcommands#89]
I was wondering if you could make a client or a mod with the /cbook command on the 1.8 version

**Comment by MCRcortex** [comment]
no, sorry old versions are not supported in any way shape or form, you can try backport the 1.12 version if you really need

**Comment by TG310** [comment]
How can I backport the 1.12 version

**Comment by hube12** [comment]
you modify the gradle build with 

> version = "1.8-11.14.4.1577"
    runDir = "run"
    mappings = "snapshot_20151128"

and 

> dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }

Then you run 
`gradlew jar` and gather all the errors, and fix one by one ...
