### ISSUE TITLE
/cenchant (efficiency?) is inaccurate

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#91]
trying to enchant a book using /cenchant using only efficiency is not accurate half of the time
(i think it might only be efficiency, since other enchantments are a lot more consistent)

video:https://youtu.be/oqd0BQ97lng
 ^ this is done under 1.14.4 singleplayer

**Comment by Earthcomputer** [comment]
There is a chest in the way, so you only have 14 bookshelves there.
By the way, thanks for the video, I wish everyone did that, it makes my life very easy :)

**Comment by ghost** [comment]
ah, how could i forget about that. thanks.
