### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#93]
Hey,
you added the cscript command a while ago, but i cant find any documentation about how to use it anywhere.
Am i missing something?

**Comment by Earthcomputer** [comment]
Currently the documentation is [here](https://github.com/Earthcomputer/clientcommands/blob/fabric/docs/clientcommands.ts) and there are example scripts in the docs folder. I have been wanting to put documentation for `/cscript` and the other commands on my website, too, but haven't had the time yet.

**Comment by leumasme** [comment]
I would recomment putting the documentation for cscript and other commands on the GitHub Wiki page, wich you have already enabled for this repo but are currently not using.

**Comment by Earthcomputer** [comment]
The wiki is open for anyone to edit to document clientcommands' features if they want to. Sadly, I do not have time to maintain it myself, but if anyone want to, feel free!

**Comment by Earthcomputer** [comment]
In fact this is a duplicate of #110 (yes, I know that was reported later, but it is a more specific report)
