### ISSUE TITLE
Suggestion: /cbrightness command

### ISSUE THREAD

**Issue by ArtelGG** [Earthcomputer/clientcommands#94]
Allows the user to change their brightness/gamma to values higher than is allowed in-game currently, for example; a "fullbright" level, or, something more tame, such as 125%.
**Command(s):** `/cbrightness` `/cgamma`
**Argument(s):** `<integer>`

**Comment by Earthcomputer** [comment]
Good idea!

**Comment by Mhowser** [comment]
Adding to this, how about a command to disable client side lighting updates? This could be quite useful for very laggy areas or for old/slow computers.

Something like `/cbrightness disable updates`

**Comment by Earthcomputer** [comment]
First of all, that's too different, should go in a separate issue. Second of all, isn't there already a mod for that?

**Comment by Mhowser** [comment]
I have not encountered a mod that disables light updates only, there is Phosphor, but has no option for it.
