### ISSUE TITLE
Suggestion: add a disconnect function to the script API

### ISSUE THREAD

**Issue by silversquirl** [Earthcomputer/clientcommands#95]
This would disconnect from a server or "save and quit" in singleplayer. Would be useful for automating long tasks and then quitting to save CPU, for example. Even more useful would be functionality for logging back in, so you could automate tasks that require unloading and reloading chunks etc. but that's probably a lot more effort.

**Comment by Earthcomputer** [comment]
Good idea!
Although I think a connect to server function is a bit out of the scope of clientcommands, I could add a relog function. In fact, the old 1.12 version of clientcommands used to have `/crelog`, I just never found the time to re-add it.
