### ISSUE TITLE
Feature Request: Ghost blocks/Client side blocks

### ISSUE THREAD

**Issue by Mhowser** [Earthcomputer/clientcommands#96]
Something like `/cgive diamond_block` would give the player fake, client-side blocks to place, only existing on the client. Another command could be `/csetblock ~ ~ ~ gold_ore` or perhaps extended to `/cfill`.

**Comment by silversquirl** [comment]
`/cgive` sounds pretty difficult to implement, as you'd need to track which items are fake and which are real

**Comment by Mhowser** [comment]
`ghost:diamond_block` seems simple to track.

**Comment by Earthcomputer** [comment]
`/csetblock` is an idea, and could be useful for testing with ghost blocks. However in terms of the item, I agree with vktec, it's too difficult and not really in the scope of clientcommands to implement. You could implement it yourself with scripting though, once I add support for event-triggered scripts.

**Comment by xpple** [comment]
Closed by [this commit](https://github.com/Earthcomputer/clientcommands/commit/d65a97f5ad0a3176c825005c1d499573d75258da).
