### ISSUE TITLE
Enchantment tools not working for PaperSpigot servers (ccrackrng)

### ISSUE THREAD

**Issue by hykilpikonna** [Earthcomputer/clientcommands#98]
I tried cracking enchantment RNG with both clientcommands and enchcracker, both are not working for PaperSpigot 1.14. The /ccrackrng command runs for like a really long time, so I just clicked cancel. The enchcracker tool can only crack individual XP seeds but fails to calculate the player seed with two XP seeds.

I also checked other server applications, including Vanilla, CraftBukkit, Spigot, and they all worked.

Any workarounds for PaperSpigot?

**Comment by leumasme** [comment]
Nope, this is known and expected. Paper uses a Shared RNG for all entities. There will not be a workarround for this as it is most likely impossible to work arround.

**Comment by leumasme** [comment]
More accurately, this is the patch that breaks it https://github.com/PaperMC/Paper/blob/c034be8a825df3936bca531cb4b29d90a56b0d7e/Spigot-Server-Patches/0070-Use-a-Shared-Random-for-Entities.patch
