### ISSUE TITLE
Suggestion: sign search

### ISSUE THREAD

**Issue by silversquirl** [Earthcomputer/clientcommands#99]
Can't think of a good command name for this, but it's basically what it says on the tin: searches all signs within a radius for some text. Nice additional features would be regex, fuzzy matching, etc.

**Comment by leumasme** [comment]
Oh yeah this would be useful. Had to search many big signshops by hand and wished that i had this...

**Comment by Mhowser** [comment]
adding on to this, It would be great to have a cscript function to find signs in the world and record their contents and coordinates to a log.

**Comment by Earthcomputer** [comment]
You can already do this with scripts, using tile entity NBT

**Comment by Earthcomputer** [comment]
`/csignsearch` in next release
